 module.exports = {
				"STR_COREPLAY_BUTTON_FOLD":"Fold",
				"STR_COREPLAY_BUTTON_CHECK":"Check",
				"STR_COREPLAY_BUTTON_CALL":"Call %s",
				"STR_COREPLAY_BUTTON_RAISE":"Raise",
				"STR_COREPLAY_BUTTON_CONFIRM":"Confirm",
				"STR_COREPLAY_BUTTON_ALLIN":"All-In",
				"STR_COREPLAY_BUTTON_PREP_CHECKORFOLD":"Check/Fold",
				"STR_COREPLAY_BUTTON_PREP_AUTOCHECK":"Check",
				"STR_COREPLAY_BUTTON_PREP_CALL":"Call %s",
				"STR_COREPLAY_BUTTON_PREP_CALLANY":"Call Any",
				"STR_INFORMATION_TILLE_1":"INFORMATION",
				"STR_INFORMATION_TILLE_2":"ITEMS LIST",
				"STR_INFORMATION_TILLE_3":"QUICK WORDS",
				"STR_INFORMATION_TILLE_4":"QUICK VOICES",
				"STR_INFORMATION_TILLE_5":"STATISTICS",
				"STR_INFORMATION_PERSONAL_LV":"Level",
				"STR_INFORMATION_PERSONAL_ID":"ID",
				"STR_INFORMATION_PERSONAL_NAME":"Name",
				"STR_INFORMATION_PERSONAL_MALE":"Male",
				"STR_INFORMATION_PERSONAL_FEMALE":"Female",
				"STR_INFORMATION_PERSONAL_ADDRESS":"Address: ",
				"STR_INFORMATION_PERSONAL_ADDRESS_NULL":"Unknown",
				"STR_INFORMATION_PERSONAL_SIGNATURE":"Signature:",
				"STR_INFORMATION_PERSONAL_PHOTO_DEFAULT":"NEW PHOTO",
				"STR_INFORMATION_PERSONAL_PHOTO_INREVIEW":"IN REVIEW",
				"STR_INFORMATION_ITEMLIST_TIME":"Day",
				"STR_INFORMATION_ITEMLIST_TIME_HOUR":"Hour",
				"STR_INFORMATION_QUICKCHAT_WORDS":"Quick Words %d",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_1":"The game started off, and I'm prepared to win!",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_2":"Don't waste time, please make your play.",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_3":"I got very strong cards to win this time.",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_4":"I'm going to All-In. Fold your cards quickly if you are afraid.",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_5":"I won this hand, and I certainly won't hold back on you on the next.",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_6":"\"Fold\" doesn't mean I lose. I just want to take a break.",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_7":"I have to say you play cards surprisingly well.",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_8":"I can't believe this thing could happen.",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_9":"I didn't play seriously, next time I won't lose.",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_10":"You are so lucky I am leaving now.",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_NULL":"Click here to enter your Quick Words",
				"STR_INFORMATION_QUICKCHAT_VOICE":"Quick Voice %d",
				"STR_INFORMATION_QUICKCHAT_VOICE_DEFAULT":"Hold here to record",
				"STR_INFORMATION_QUICKCHAT_VOICE_ENTERTITLE":"Click here to enter the title",
				"STR_INFORMATION_QUICKCHAT_VOICE_RECORDING":"Recording",
				"STR_INFORMATION_STATISTICS_ID":"ID:",
				"STR_INFORMATION_STATISTICS_GAMES":"Hands:",
				"STR_INFORMATION_STATISTICS_WINS":"Win",
				"STR_INFORMATION_STATISTICS_LOSE":"Lose",
				"STR_INFORMATION_STATISTICS_WINRATE":"Win Rate:",
				"STR_INFORMATION_STATISTICS_SHOWINRIVER":"Show in River:",
				"STR_INFORMATION_STATISTICS_FOLDINPREFLOP":"Pre-flop Fold:",
				"STR_INFORMATION_STATISTICS_ALLININPREFLOP":"Pre-flop All-In:",
				"STR_INFORMATION_STATISTICS_HIGHESTCHIP":"Most Chips:",
				"STR_INFORMATION_STATISTICS_MOSTWIN":"Biggest Pot Won:",
				"STR_INFORMATION_STATISTICS_BESTCARDS":"Best Hand:",
				"STR_INFORMATION_STATISTICS_GIVECHIPTOFRIEND":"Sent Free Chips to Friends",
				"STR_INFORMATION_STATISTICS_GIVECHIPTOFRIEND_TIMES":"Times",
				"STR_INFORMATION_STATISTICS_GIVECHIPINGAME":"Gave Chips to Other Players",
				"STR_INFORMATION_STATISTICS_GIVECHIPINGAME_TIMES":"Times",
				"STR_INFORMATION_ITEMLIST_ITEM_TITLE":"YOU HAVE:",
				"STR_INFORMATION_ITEMLIST_PATCH_TITLE":"YOU CAN CHANGE:",
				"STR_RANKING_TITLE_MAIN":"RANKING",
				"STR_RANKING_TITLE_1":"TOP CHIPS",
				"STR_RANKING_TITLE_2":"EARNING RATE",
				"STR_RANKING_TITLE_3":"GAIN TODAY",
				"STR_RANKING_TITLE_4":"WINS TODAY",
				"STR_RANKING_TITLE_5":"INTERACTION",
				"STR_RANKING_GMT_GMT":"GMT",
				"STR_RANKING_GMT_EXPLAIN":"The server uses the GMT as the time standard. So the GMT is displayed in our game. Please be attention.",
				"STR_RANKING_TOP_TOP":"TOP",
				"STR_RANKING_RANKING_NOPLAYER":"No player in the ranking list.",
				"STR_CHAT_EXPRESSION_TITLE":"Expressions",
				"STR_CHAT_QUICKWORDS_TITLE":"Quick Words",
				"STR_CHAT_QUICKVOICES_TITLE":"Quick Voices",
				"STR_CHAT_INPUT_DEFAULT":"Please enter text here",
				"STR_CHAT_INPUT_DEFAULT_IOS":"Please enter text here",
				"STR_CHAT_QUICKVOICE_NOVICE":"No Quick Voice",
				"STR_CHAT_QUICKVOICE_NOTITLE":"No description",
				"STR_TABLEBOARD_CAHT_NOQUICKVOICE":"You haven't recorded any Quick Voices yet.",
				"STR_TABLEBOARD_CHAT_NOQUICKTEXT":"You haven't recorded any Quick Words yet.",
				"STR_TABLEBOARD_RECORDING_COUNTDOWN":"Remain %d seconds",
				"STR_FRIENDS_TITLE":"YOUR FRIENDS",
				"STR_FRIENDS_NOFRIENDS":"You have no friends so far. Please click the searching botton on the top right corner to find the player by using the player's nickname. Also, you can click the player's portrait in Play Table UI or Main UI to send the friend request. Go and try it now!",
				"STR_FRIENDS_FRIENDS_UPDATE":"Show friends who updated new photos first",
				"STR_FRIENDS_FRIENDS_OL":"Show online friends first",
				"STR_FRIENDS_FRIENDS_ACTIVE":"Show active friends first",
				"STR_FRIENDS_FRIENDS_MAX":"MAX",
				"STR_FRIENDS_FRIENDS_INFORMATION_LV":"Level",
				"STR_FRIENDS_FRIENDS_INFORMATION_MALE":"Male",
				"STR_FRIENDS_FRIENDS_INFORMATION_FEMALE":"Female",
				"STR_FRIENDS_FRIENDS_INFORMATION_ADDRESS":"Address: ",
				"STR_FRIENDS_FRIENDS_INFORMATION_DEFAULT":"Likes, comments and free Chips you gave to this friend.",
				"STR_FRIENDS_FRIENDS_INFORMATION_NOPHOTO":"This player haven't uploaded any photos.",
				"STR_FRIENDS_FRIENDS_INFORMATION_GAMES":"Hands:",
				"STR_FRIENDS_FRIENDS_INFORMATION_WIN":"Win",
				"STR_FRIENDS_FRIENDS_INFORMATION_LOSE":"Lose",
				"STR_FRIENDS_FRIENDS_INFORMATION_WINRATE":"Win Rate:",
				"STR_FRIENDS_FRIENDS_INFORMATION_SHOWINRIVER":"Show in River:",
				"STR_FRIENDS_FRIENDS_INFORMATION_FOLDINPREFLOP":"Pre-flop Fold:",
				"STR_FRIENDS_FRIENDS_INFORMATION_ALLININPREFLOP":"Pre-flop All-In:",
				"STR_FRIENDS_FRIENDS_INFORMATION_HIGHESTCHIP":"Most Chips:",
				"STR_FRIENDS_FRIENDS_INFORMATION_MOSTWIN":"Biggest Pot Won:",
				"STR_FRIENDS_FRIENDS_INFORMATION_BESTCARDS":"Best Hand:",
				"STR_FRIENDS_FRIENDS_SEARCHTITLE":"SEARCH PLAYERS",
				"STR_FRIENDS_FRIENDS_SEARCHTIPS":"Please enter at least four characters to search one player's nickname.",
				"STR_FRIENDS_FRIENDS_SEARCH":"Find %d player(s) according to the players' nickname. At most display %d players.",
				"STR_LOGIN_PHONELOGIN":"Phone Login",
				"STR_LOGIN_ACCOUNTLOGIN":"Account Login",
				"STR_LOGIN_FACEBOOKLOGIN":"FACEBOOK Login",
				"STR_LOGIN_GUESTLOGIN":"Guest Login",
				"STR_LOGIN_ACCOUNTLOGIN_ACCOUNT":"Please enter your email address ",
				"STR_LOGIN_ACCOUNTLOGIN_PASSWORD":"Please enter your password",
				"STR_LOGIN_ACCOUNTLOGIN_AUTOLOGIN":"Auto Login",
				"STR_LOGIN_ACCOUNTLOGIN_RETRIEVEPASSWORD":"Request Password",
				"STR_LOGIN_ACCOUNTLOGIN_LOGIN":"LOGIN",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTER":"REGISTER",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTERACCOUNT":"Please enter your email address ",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTERENTERPASSWORD":"Please enter your password",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTERCONFRIMPASSWORD":"Confirm Password",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTERREGISTER":"REGISTER",
				"STR_LOGIN_ACCOUNTLOGIN_RETRIEVEPASSWORD_EXPLAIN":"If you forgot your password, please enter the email address used for registration. We will send a new password to this email.",
				"STR_LOGIN_ACCOUNTLOGIN_RETRIEVEPASSWORD_ENTER":"Please enter your registration email address",
				"STR_LOGIN_ACCOUNTLOGIN_RETRIEVEPASSWORD_SENDEMAIL":"SEND EMAIL",
				"STR_LOGIN_TERMSOFSERVICE":"TERMS OF SERVICE",
				"STR_LOBBY_TITLE":"CASINO LOBBY",
				"STR_LOBBY_ID":"ID",
				"STR_LOBBY_BLIND":"Blind %s/%s",
				"STR_LOBBY_5PLAYERS":"5 Players",
				"STR_LOBBY_9PLAYERS":"9 Players",
				"STR_LOBBY_FULL":"Full Room",
				"STR_LOBBY_EMPTY":"Empty Room",
				"STR_SIT_ROOMID":"ROOM ID %d",
				"STR_SIT_BLIND":"Small/Big Blind %s/%s",
				"STR_SIT_MINBLIND":"MIN",
				"STR_SIT_MAXBLIND":"MAX",
				"STR_SIT_AUTOSIT":"Auto take chips and sit down when chip is not enough.",
				"STR_SIT_LEAVE":"LEAVE",
				"STR_SIT_SIT":"SIT DOWN",
				"STR_SIT_NOCHIP":"Your chip is not enough.",
				"STR_SIT_SHOP":"SHOP",
				"STR_INVITE_TITLE":"PLAY WITH YOUR FRIENDS!",
				"STR_INVITE_BUTTON":"CALL TO TABLE",
				"STR_INVITE_NOFRIEND":"Currently there is nobody on your friends list. Go and make some friends! ",
				"STR_INVITE_UNKNOWN":"Address\nUnknown",
				"STR_MES_FRIEND_TITLE":"FRIEND MESSAGE",
				"STR_MES_SYSTEM_TITLE":"SYSTEM MESSAGE",
				"STR_MES_ADDFRIEND_RCCEIVE":"Do you want to accept %s as your friend?",
				"STR_MES_ADDFRIEND_AGREE":"%s accepted you as his/her friend. You can find %s in your friends list.",
				"STR_MES_ADDFRIEND_YOUAGREE":"Your accepted %s as your friend. You can find him/her in your friends list.",
				"STR_MES_CHIPS_GIVE":"%s gave you %d free chips. Click to accept.",
				"STR_MES_CHIPS_RECEIVE":"You acceptd %d free chips from %s.",
				"STR_MES_MESSAGE_NULL":"There's no message so far.",
				"STR_MES_MONTH_JAN":"Jan.",
				"STR_MES_MONTH_FEB":"Feb.",
				"STR_MES_MONTH_MAR":"Mar.",
				"STR_MES_MONTH_APR":"Apr.",
				"STR_MES_MONTH_MAY":"May",
				"STR_MES_MONTH_JUN":"Jun.",
				"STR_MES_MONTH_JUL":"Jul.",
				"STR_MES_MONTH_AUG":"Aug.",
				"STR_MES_MONTH_SEP":"Sep.",
				"STR_MES_MONTH_OCT":"Oct.",
				"STR_MES_MONTH_NOV":"Nov.",
				"STR_MES_MONTH_DEC":"Dec.",
				"STR_HOMESCREEN_OLPLAYER":"%s Players Online!",
				"STR_HOMESCREEN_PHOTOUPLOAD":"Your friend %s uploaded new photos.",
				"STR_HOMESCREEN_NOUPLOAD":"No friends uploaded photos.",
				"STR_EVENT_BACK":"BACK",
				"STR_ANNOUNCEMENT_TITLE":"ANNOUNCEMENT",
				"STR_PLAYER_INF_NAME":"Name:",
				"STR_PLAYER_INF_TITLE_PHOTO":"PHOTOS",
				"STR_PLAYER_INF_TITLE_ACHIEVEMENTS":"ACHIEVEMENTS",
				"STR_PLAYER_INF_LV":"Level",
				"STR_PLAYER_INF_MALE":"Male",
				"STR_PLAYER_INF_FEMALE":"Female",
				"STR_PLAYER_INF_ADDRESS":"Address: ",
				"STR_PLAYER_INF_BUTTON_BLOCK":"Click here to block this player",
				"STR_PLAYER_INF_BLOCKBUTTON":"BLOCK",
				"STR_PLAYER_INF_BUTTON_UNLOCK":"Click here to unblock this player",
				"STR_PLAYER_INF_UNLOCKBUTTON":"UNBLOCK",
				"STR_PLAYER_INF_BUTTON_REPORT":"Click here to report this player's portrait",
				"STR_PLAYER_INF_REPORTBUTTON":"REPORT",
				"STR_PLAYER_INF_BLOCK":"After blocking, you will not receive any message, voice or emoji from this player. Are you sure to block this player?",
				"STR_PLAYER_INF_UNBLOCK":"Unblock this player, you can receive the message, voice or emoji from this player again.",
				"STR_PLAYER_INF_REPORT":"Report this player if you feel sick about his/her portrait. And his/her portrait will be blocked through several reports. We will review the portrait as soon as possible. Are you sure to report this portrait?",
				"STR_PLAYER_PHOTO_NULL":"This player haven't uploaded any photos.",
				"STR_CHECKPHOTO_NOAUTHORITY":"Sorry, you can't access this page due to the player's privacy settings.",
				"STR_PLAYER_PHOTO_CRITICTITLE":"Comment",
				"STR_PLAYER_STATISTICS_GAMES":"Hands:",
				"STR_PLAYER_STATISTICS_WINS":"Win",
				"STR_PLAYER_STATISTICS_LOSE":"Lose",
				"STR_PLAYER_STATISTICS_WINRATE":"Win Rate:",
				"STR_PLAYER_STATISTICS_SHOWINRIVER":"Show in River:",
				"STR_PLAYER_STATISTICS_FOLDINPREFLOP":"Pre-flop Fold:",
				"STR_PLAYER_STATISTICS_ALLININPREFLOP":"Pre-flop All-In:",
				"STR_PLAYER_STATISTICS_HIGHESTCHIPS":"Most Chips:",
				"STR_PLAYER_STATISTICS_MOSTWIN":"Biggest Pot Won:",
				"STR_PLAYER_STATISTICS_BTESTCARD":"Best Hand:",
				"STR_PLAYER_STATISTICS_MINS":"%s mins",
				"STR_PLAYER_ACHIEVEMENT_NULL":"This player has not unlocked any achievements yet.",
				"STR_LOGINREWARD_TITLE":"LOGIN REWARD",
				"STR_LOGINREWARD_DAY":"DAY %d",
				"STR_LOGINREWARD_RECEIVED":"Have received",
				"STR_LOGINREWARD_TIPS":"If you keep continuous login,you can get more huge rewards.",
				"STR_LOGINREWARD_SUCCESS":"You got %d %s by daily login.",
				"STR_ABOUTUS_STAFF":"Poker Royal Texas Hold'em Staff List\n\n\nGameDesinger\n\nStone\nJohn Smith\n\n\nProgrammer\n\nJack\nWillian\nHaven \nSpiro\nBob\nRussell\n\n\nArtDesinger\n\nPantheon\nEmma\nMandy\n\n\nGameTester\n\nJoffence\nDoris\n\n\nSpecial Thanks\n\nChris\nAlex\nMatata\nBlank",
				"STR_BUTTON_YES":"YES",
				"STR_BUTTON_NO":"NO",
				"STR_BUTTON_OK":"OK",
				"STR_BUTTON_IGNORE":"IGNORE",
				"STR_BUTTON_AGREE":"AGREE",
				"STR_OPTIONS_TITLE":"OPTIONS",
				"STR_OPTIONS_VOICE":"VOICE",
				"STR_OPTIONS_SOUND":"SOUND",
				"STR_OPTIONS_AUTOSIT":"SIT DOWN AUTO",
				"STR_OPTIONS_VIBRATION":"VIBRATION",
				"STR_OPTIONS_FOLLOW":"ALLOW FRIENDS TO FOLLOW",
				"STR_OPTIONS_INVITE":"RECIEVE INVATATION MESSAGE",
				"STR_OPTIONS_SEEPHOTOS":"WHO CAN SEE MY PHOTOS",
				"STR_OPTIONS_CHOSEN_YES":"Yes",
				"STR_OPTIONS_CHOSEN_NO":"No",
				"STR_OPTIONS_SEEPHOTOS_FRIEND":"Only friends",
				"STR_OPTIONS_SEEPHOTOS_NOONE":"No one",
				"STR_OPTIONS_SEEPHOTOS_ANYONE":"Anyone",
				"STR_OPTIONS_RATE":"RATE OUR GAME",
				"STR_OPTIONS_CACHE":"CLEAR PORTRAIT CACHE",
				"STR_OPTIONS_CACHE_CONFIRM":"Clear cache will delete the portraits and photos you downloaded. Are you sure you want to clear the cache?",
				"STR_OPTIONS_CACHE_CLEARED":"Clear cache successed",
				"STR_OPTIONS_ABOUT":"ABOUT US",
				"STR_OPTIONS_REPORT":"Report issues",
				"STR_OPTIONS_FOLLOWUS":"Follow us @FaceBook",
				"STR_OPTIONS_CONTACT":"CONTACT US",
				"STR_LOADING_1":"Bring your friends to play our game together. Also, don't forget to play with them offline.",
				"STR_LOADING_2":"Please be polite when communicating with others. It's the way to repect each other.",
				"STR_LOADING_3":"No matter how handsome and beautiful the dealers are, never try to take liberties with them in game.",
				"STR_LOADING_4":"Never give up when you meet setback in game, the life will not abandon you.",
				"STR_LOADING_5":"Do everything in moderation including play Poker Royal.",
				"STR_LOADING_6":"Remember to send free chips to your friends at their player profile every day.",
				"STR_LOADING_7":"Click the chip symbol in the botton left corner to chose how much you want to raise .",
				"STR_LOADING_8":"You can block an opponent's chat messages by clicking the player's avatar in his player profile.",
				"STR_LOADING_9":"Click the voice button in another player's profile to send a private message.",
				"STR_LOADING_10":"Don't forget to check the activities daily. There might be a a new bonus waiting for you.",
				"STR_LOADING_11":"The rewards will grow better with every continuous login.",
				"STR_LOADING_END":"Maintaining peace of mind. Do not pleased by external gains or saddened by personal losses.",
				"STR_TABLEBOARD_ID":"Room ID %d Blind %s/%s",
				"STR_CARDTYPE_HIGH_CARD":"HIGH CARD",
				"STR_CARDTYPE_PAIR_CARD":"A PAIR",
				"STR_CARDTYPE_TWO_PAIRS_CARD":"TWO PAIRS",
				"STR_CARDTYPE_THREE_CARD":"THREE OF A KIND",
				"STR_CARDTYPE_STRAIGHT":"STRAIGHT",
				"STR_CARDTYPE_FLUSH":"FLUSH",
				"STR_CARDTYPE_FULL_HOUSE":"FULL HOUSE",
				"STR_CARDTYPE_FOUR_OF_A_KIND":"FOUR OF A KIND",
				"STR_CARDTYPE_STRAIGHT_FLUSH":"STRAIGHT FLUSH",
				"STR_CARDTYPE_ROYAL_FLUSH":"ROYAL STRAIGHT FLUSH",
				"STR_TABLEBOARD_EXP":"EXP",
				"STR_QUESTS_TITLE":"QUESTS",
				"STR_QUESTS_RECEIVEBUTTON":"RECEIVE",
				"STR_ACHIEVEMENTS_TITLE":"ACHIEVEMENTS",
				"STR_LVUP_TITLE":"CONGRATULATIONS",
				"STR_LVUP_TEXT":"You reached Level %d and got the rewards %s chips.",
				"STR_SHOP_TITLE":"SHOP",
				"STR_SHOP_BUTTON":"BUY",
				"STR_ALMS_TITLE":"RENASCENCE",
				"STR_ALMS_TEXT":"Your chips and diamonds is not enough, you have %d chance(s) left to get %s free chips today.",
				"STR_BUG_REPORT":"Click here to submit your new problem",
				"STR_BUG_INPUT":"Please enter your questions.",
				"STR_BUG_TIP":"Your questions have been submitted. We will answer your question as soon as possible. ",
				"STR_BUG_TIME":"Submission Time",
				"STR_BUG_WAIT":"Wait for the reply",
				"STR_BUG_RESPONSETIME":"Reply Time",
				"STR_BUG_DELTIP":"Are you sure to delete this question?",
				"STR_BUG_VIEW":"View Details ",
				"STR_BUG_COMMIT":"Commit",
				"STR_BUG_DELTIPDONE":"Delete Success!",
				"STR_BUG_DELTIPFAIL":"Delete Fail!",
				"STR_BUG_COMMIT_TIP":"Commit Fail!",
				"STR_POKER_ROOM_BET":"Bet %s/%s",
				"STR_POKERTABLEBOARD_ID":"Room ID %d Min/Max Bet %s/%s",
				"STR_POKER_PRE_BET":"Bet",
				"STR_POKER_TYPE_POK9":"Pok9",
				"STR_POKER_TYPE_POK8":"Pok8",
				"STR_POKER_TYPE_TONG":"Tong",
				"STR_POKER_TYPE_SAM_LUEANG":"Sam Lueang",
				"STR_POKER_TYPE_STRAIGHT_FLUSH":"Straight Flush",
				"STR_POKER_TYPE_STRAIGHT":"Straight",
				"STR_POKER_TYPE_SCORE_0":"Score 0",
				"STR_POKER_TYPE_SCORE_1":"Score 1",
				"STR_POKER_TYPE_SCORE_2":"Score 2",
				"STR_POKER_TYPE_SCORE_3":"Score 3",
				"STR_POKER_TYPE_SCORE_4":"Score 4",
				"STR_POKER_TYPE_SCORE_5":"Score 5",
				"STR_POKER_TYPE_SCORE_6":"Score 6",
				"STR_POKER_TYPE_SCORE_7":"Score 7",
				"STR_POKER_TYPE_SCORE_8":"Score 8",
				"STR_POKER_TYPE_SCORE_0_9":"Score 0-9",
				"STR_POKER_TYPE_SCORE_9":"Score 9",
				"STR_POKER_INTRUUCE":"Card type description",
				"STR_POKER_INTRUUCE1":"The force of the cards is sorted from top to bottom",
				"STR_POKER_INTRUUCE2":"These cards are 0 points",
				"STR_POKER_INTRUUCE3":"These cards are 1-9 points",
				"STR_POKER_INTRUUCE4":"Add up all your card's points and take the single digits",
				"STR_POKER_INTRUUCE5":"2 initial cards' points is 9 ",
				"STR_POKER_INTRUUCE6":"2 initial cards' points is 8",
				"STR_POKER_INTRUUCE7":"KA2.A23 is not straight",
				"STR_POKER_INTRUUCE8":"Odds multiples of the card type",
				"STR_POKER_INTRUUCE9":"2 cards flush",
				"STR_POKER_INTRUUCE10":"3 cards flush",
				"STR_POKER_INTRUUCE11":"After the game is over, you will leave your seat",
				"STR_POKER_INTRUUCE12":"After the game is over, you will leave your seat and exit room",
				"STR_WIN_STREAK":"Winning Streak:",
				"STR_PLAYER":"Player",
				"STR_DEAR":"Dear",
				"STR_GAME_GOTODEAR":"Click Go Dear",
				"STR_CHIP_NOT_ENOUGH":"Your chip is not enough.At least %s chips can change dealer .Do you go to the store?",
				"STR_POKERTABLEBOARD_ID1":"Min/Max Bet %s/%s",
				"STR_GAME_GOTODEAR_1":"Dealer change success, 5 times after you can leave dealer's seat.\n",
				"STR_GAME_GOTODEAR_2":"A Player Go Dear Success!",
				"STR_STATIC_BIGWIN":"Biggest Win:\n",
				"STR_CARDTYPE100":"3 card group JQK",
				"STR_CARDTYPE101":"Straight Flush",
				"STR_CARDTYPE102":"A PAIR",
				"STR_CARDTYPE103":"Straight",
				"STR_CARDTYPE104":"The three CARDS are the order",
				"STR_ADDFRIEND_ONESELF":"You can not add more friends now. If you want to increase your friends limit, please buy the Mail List item at the shop.",
				"STR_ADDFRIEND_OTHERS":"Unfortunately, the player's number of friends has reached the limit. You can not add him as a friend right now.",
				"STR_MESSRECEIVE_UNDONE":"You have got all the attached things in this message.",
				"STR_LOGIN_WORNING":"Your account was frozen. If you have any questions, please contact the customer service.",
				"STR_LOGIN_INFO_ERROR":"Unable to log in. Please ensure that your email and password are correct.",
				"STR_LOGIN_INFO_NULL":"Account and password can not be blank. Please enter.",
				"STR_LOGIN_EMALL_REGISTERED":"This email is already registered. Please use a different one.",
				"STR_LOGIN_EMAIL_ERROR":"Wrong email format. Please check again.",
				"STR_LOGIN_PASSWORD_SHORT":"The password should consist of 6-16 letters or numbers. Please re-enter your password.",
				"STR_LOGIN_PASSWORD_DIFFERENT":"Password and confirmation password do not match. Please double-check.",
				"STR_LOGIN_PASSWORD_CHARACTER":"The password can only include numbers and letters. Please re-enter your password.",
				"STR_LOGIN_REGISTER_SUCCESS":"Congratulations, you have successfully registered your account. Click Ok to join the game now.",
				"STR_LOGIN_RETRIEVE_SUCCESS":"Password recovery email has been sent. Please check your mailbox. Please wait if there is some delay.",
				"STR_LOGIN_RETRIEVE_FAIL":"The email address entered is not connected to a registered account. Please double-check.",
				"STR_MAIN_LOGOFF":"Are you sure you want to log out? ",
				"STR_MAIN_QUIT":"Are you sure to close our game?",
				"STR_SHOP_CHIP":"You do not have enough chips. Do you want to buy some at the shop?",
				"STR_SHOP_DIAMOND":"You do not have enough diamonds. Do you want to buy some at the shop?",
				"STR_SHOP_BUYSUCCESSFUL":"You have successfully purchased the goods %s.",
				"STR_SHOP_REACHLIMIT":"You reach the purchasing limitaton of this item.",
				"STR_SHOP_BUYFAIL":"Sorry, trade failed, please try it again.",
				"STR_PLAYERSEARCH_SHORT":"Please enter 4 characters at least to search for a friend.",
				"STR_PLAYERSEARCH_LONG":"Please enter 16 characters at most to search for a friend.",
				"STR_FRIEND_HAVEADDED":"This player is already existed in your friend list.",
				"STR_FRIEND_LIMIT":"You can not add more friends now. If you want to increase your friends limit, please buy the Mail List item at the shop.",
				"STR_FRIEND_FOLLOW":"Are you sure you want to join your friend %s's table? The Bet are %d/%d.",
				"STR_FRIEND_DEL":"Are you sure you want to remove this friend from your friends list?",
				"STR_FRIEND_ADDYOURSELF":"You can't add yourself to your friends list.",
				"STR_PRESENT_NOTFRIEND":"Sorry, free chips only can be given to the one who is your friend.",
				"STR_PRESENT_DONE":"You have already given the free chips to this friend today. Please try again tomorrow.",
				"STR_PERSONAL_NAME_SHORT":"Your nickname should be at least 4 letters or numbers.",
				"STR_PERSONAL_NAME_LONG":"Your nickname should be no more than 16 letters or numbers.",
				"STR_PERSONAL_NAME_REPEAK":"This nickname already exists. Please enter a new one.",
				"STR_PERSONAL_NAME_ILLEGAL":"This nickname includes characters that are not supported. Please retry using only numbers and letters.",
				"STR_PERSONAL_SIGNATURE_LONG":"Your signature is too long. Please stay within 120 characters.",
				"STR_PERSONAL_RECORDING_SHORT":"The recording time is too short.",
				"STR_PERSONAL_QUICKVOICE_PLAY":"Only one voice can be played at a time.",
				"STR_PERSONAL_QUICKVOICE_RECORD":"Can't record voice messages when another one is playing.",
				"STR_PERSONAL_QUICKVOICE_DEL":"Are you sure you want to delete this Quick Voice?",
				"STR_PERSONAL_PHOTO_DEL":"Are you sure you want to delete this photo?",
				"STR_PERSONAL_PHOTO_LIMIT":"You can not upload more photos now. If you want to increase your photo limit, please buy the Album item at the shop.",
				"STR_PERSONAL_ACCOUNT_BINDING":"This email is already registered. Please use a different one.",
				"STR_PERSONAL_ITEMEXCHANGE_301002":"Congratulations! You have successfully exchange %d Diamond. The equal patch of Diamond will be deducted automatically.",
				"STR_PERSONAL_ITEMEXCHANGE_302003":"Congratulations! You have successfully exchange %d Magnifier. The equal patch of Magnifier will be deducted automatically.",
				"STR_PERSONAL_ITEMEXCHANGE_302001":"Congratulations! You have successfully exchange %d Microphones. The equal patch of Microphone will be deducted automatically.",
				"STR_PERSONAL_ITEMEXCHANGE_302002":"Congratulations! You have successfully exchange %d Emoji. The equal patch of Emoji will be deducted automatically.",
				"STR_PERSONAL_BINDIN":"Please connect your email address to your account. So, you can use this account to log in from other devices.",
				"STR_ITEM_TUREEYE_NULL":"Magnifier is not enough. You should go shopping now.",
				"STR_REPORT_PHOTO_CONFRIM":"Are you sure you want to report this photo? After several reports it will be blocked. We will review it as soon as possible.",
				"STR_REPORT_PHOTO_REPEAK":"You have already reported this photo.",
				"STR_SITDOWN_LIMIT":"This room is full. Please try another one.",
				"STR_SITDOWN_FULL":"This room is full. Click \"Yes\" to be automatically matched to a new room, or \"No\" to stay in the current room.",
				"STR_SITDOWN_REPEAK":"You have sat down.",
				"STR_SITDOWN_NOTEMPTY":"Please choose another seat, this seat is occupied.",
				"STR_TABLE_RECORDIND_SHORT":"The recording time is too short. Please try again.",
				"STR_ITEM_VOICE_NULL":"Microphone is not enough. Shopping now!",
				"STR_ITEM_VOICE_STAND":"You need to sit down to use the Voice function.",
				"STR_ITEM_CHAT_STAND":"You need to sit down to interact with other players.",
				"STR_ITEM_EXPRESSION_NULL":"Emoji is not enough. Shopping now!",
				"STR_TABLE_LEAVE_SEAT":"Are you sure you want to leave your seat? The chips you have bet will be lost.",
				"STR_TABLE_LEAVE_ROOM":"Are you sure you want to exit to lobby? The chips you have bet will be lost.",
				"STR_INVITE_RECEIVE":"%s invites you to join his/her game. Click here to confirm.",
				"STR_INVITE_CONFRIM":"%s invites you to join his/her game. The room ID is %d, Blind %s/%s. Are you sure to join?",
				"STR_INVITE_CONFRIM1":"%s invites you to join his/her game. The room ID is %d, Bet %s/%s. Are you sure to join?",
				"STR_INVITE_SAMEROOM":"This player and you are in the same room now.",
				"STR_MISSION_COMPLETE":"You have completed a quest. Go to reap your reward!",
				"STR_MUTE_ON":"You have activated the mute function.",
				"STR_MUTE_OFF":"You have deactivated the mute function.",
				"STR_EQUIPMENT_MICROPHONE":"Recording failed. Please look in your phone settings to check whether you allow this game to use your microphone.",
				"STR_ACHIEVEMENT_SUCCESS":"Congratulations! You receive the achievement reward %d %s.",
				"STR_LOGIN_OTHERDEVICES":"Your account has currently logined from another device. If that is not you, please change your password and contact the customer service immediately.",
				"STR_NETWORK_REQUEST":"Error %d ,network request failed. Please check your internet connection and try again.",
				"STR_NETWORK_ERROR_CHECK":"Network error. Please check your device or the network setting.",
				"STR_UNKNOWN_ERROR":"Unknow error ooccurred, the game can not operate normally. Please contact our customer service email to report this unknow error.",
				"STR_ERROR_DATA":"Game data error,please login again.",
				"STR_EVALUATION_TEXT":"Dear player, you could rate our game now. A well bonus will be awarded after your rating. Do you want to rate it now?",
				"STR_GOOGLEPLAY_ERROR_1":"This purchase action requires one or more Google Play services that are not currently available. ",
				"STR_GOOGLEPLAY_ERROR_2":"This purchase action requires an update for Google Play Services.",
				"STR_GOOGLEPLAY_ERROR_3":"This purchase action won't run without Google Play services, which are missing from your phone.",
				"STR_GOOGLEPLAY_ERROR_4":"This purchase action won't work unless you enable Google Play services.",
				"STR_ITEM_NAME_301001":"Chips",
				"STR_ITEM_NAME_301002":"Diamond(s)",
				"STR_ITEM_NAME_302001":"Microphones",
				"STR_ITEM_NAME_302002":"Emoji",
				"STR_ITEM_NAME_302003":"Magnifiers",
				"STR_ITEM_NAME_303001":"Golden Chip",
				"STR_ITEM_NAME_304001":"Mail List",
				"STR_ITEM_NAME_304002":"Album",
				"STR_ITEM_DESC_301001":"Present the total chips of players. And it is the measurement of property.",
				"STR_ITEM_DESC_301002":"Present the total diamonds of players. And it is the measurement of property.",
				"STR_ITEM_DESC_302001":"Necessary item to use the voice function. For every voice message, a Microphone is used up.",
				"STR_ITEM_DESC_302002":"Necessary item to use Emoji. For every Emoji used, one is used up.",
				"STR_ITEM_DESC_302003":"Use this item to peek at your opponent's poker statistics. One Magnifier lasts for %d mins.",
				"STR_ITEM_DESC_303001":"The Golden Chip %s the rewards received from completed quests. It lasts for %d days.",
				"STR_ITEM_DESC_304001":"It can increase the quantity of adding friends. The original ceiling is 50.One item can increase 5 more spaces. ",
				"STR_ITEM_DESC_304002":"It can increase the quantity of uploading photos. The original ceiling is 50.One item can increase 2 more spaces. ",
				"STR_GOODS_NAME_401001":"%d Diamond Pack",
				"STR_GOODS_NAME_401002":"%d Diamond Pack",
				"STR_GOODS_NAME_401003":"%d Diamond Pack",
				"STR_GOODS_NAME_401004":"%d Diamond Pack",
				"STR_GOODS_NAME_402001":"%d Chip Pack",
				"STR_GOODS_NAME_402002":"%d Chip Pack",
				"STR_GOODS_NAME_402003":"%d Chip Pack",
				"STR_GOODS_NAME_402004":"%d Chip Pack",
				"STR_GOODS_NAME_403001":"%d Microphone Pack",
				"STR_GOODS_NAME_403002":"%d Microphone Pack",
				"STR_GOODS_NAME_404001":"%d Emoji Pack",
				"STR_GOODS_NAME_404002":"%d Emoji Pack",
				"STR_GOODS_NAME_405001":"%d Magnifier Pack",
				"STR_GOODS_NAME_406001":"Golden Chip",
				"STR_GOODS_NAME_407001":"Mail List",
				"STR_GOODS_NAME_408001":"Album",
				"STR_GOODS_DESC_401001":"Contains %d Diamonds.",
				"STR_GOODS_DESC_401002":"Contains %d Diamonds",
				"STR_GOODS_DESC_401003":"Contains %d Diamonds",
				"STR_GOODS_DESC_401004":"Contains %d Diamonds",
				"STR_GOODS_DESC_402001":"Contains %d Chips",
				"STR_GOODS_DESC_402002":"Contains %d Chips",
				"STR_GOODS_DESC_402003":"Contains %d Chips",
				"STR_GOODS_DESC_402004":"Contains %d Chips",
				"STR_GOODS_DESC_403001":"Contains %d Microphones. One Microphone can be used once.",
				"STR_GOODS_DESC_403002":"Contains %d Microphones. One Microphone can be used once.",
				"STR_GOODS_DESC_404001":"Contains %d Emoji. One Emoji can be used once.",
				"STR_GOODS_DESC_404002":"Contains %d Emoji. One Emoji can be used once.",
				"STR_GOODS_DESC_405001":"Contains %d Magnifiers. Use this item to peek at your opponent's poker statistics. One Magnifier lasts for %d mins.",
				"STR_GOODS_DESC_406001":"The Golden Chip %s the rewards received from completed quests. Buying more than one will increase the duration by %d days each.",
				"STR_GOODS_DESC_407001":"The Mail List increases your friends limit. The initial level is %d, and each Mail List increases it by %d. The price will increase with purchasing volume. Moreover, all %d Mail Lists can be purchased.",
				"STR_GOODS_DESC_408001":"The Album increases your photo limit. The initial level is %d, and each Album increases it by %d. The price will increase with purchasing volume. Moreover, all %d Albums can be purchased.",
				"STR_QUEST_DESC_101101":"Play 3 hands",
				"STR_QUEST_DESC_101201":"Playing for 5 mins",
				"STR_QUEST_DESC_102101":"Win 2 hands",
				"STR_QUEST_DESC_102201":"Steal 3 pots pre-flop",
				"STR_QUEST_DESC_102301":"Win 2 hands at showdown",
				"STR_QUEST_DESC_103101":"Win a pot that is at least 5 times your bet",
				"STR_QUEST_DESC_104101":"Win a pot and at least 3 side-pots at once",
				"STR_QUEST_DESC_105101":"Win 3 hands after going All-In",
				"STR_QUEST_DESC_106101":"Win 1 hand with at least 5 players going All-In ",
				"STR_QUEST_DESC_107101":"Win 1 pot with the same hand category as your opponents at showdown",
				"STR_QUEST_DESC_108101":"Win 1 hand with HIGH CARD at showdown",
				"STR_QUEST_DESC_108201":"Win 1 hand with A PAIR at showdown",
				"STR_QUEST_DESC_108301":"Win 1 hand with TWO PAIRS at showdown",
				"STR_QUEST_DESC_108401":"Win 1 hand with 3 OF A KIND at showdown",
				"STR_QUEST_DESC_108501":"Win 1 hand with STRAIGHT at showdown",
				"STR_QUEST_DESC_108601":"Win 1 hand with FLUSH at showdown",
				"STR_QUEST_DESC_108701":"Win 1 hand with a FULL HOUSE at showdown",
				"STR_QUEST_DESC_109101":"Interact with others for 20 times",
				"STR_QUEST_DESC_110101":"Comment on others' photos for 5 times",
				"STR_QUEST_DESC_101102":"Play 10 hands",
				"STR_QUEST_DESC_101202":"Play for 15 mins",
				"STR_QUEST_DESC_102102":"Win 5 hands",
				"STR_QUEST_DESC_102202":"Steal 9 pots pre-flop",
				"STR_QUEST_DESC_102302":"Win 5 hands at showdown",
				"STR_QUEST_DESC_103102":"Win a pot that is at least 5 times your bet for 3 times",
				"STR_QUEST_DESC_104102":"Win a pot and at least 3 side-pots for 2 times",
				"STR_QUEST_DESC_105102":"Win 9 hands after going All-In",
				"STR_QUEST_DESC_106102":"Win 2 hands with at least 5 players going All-In",
				"STR_QUEST_DESC_107102":"Win 2 pots with the same hand category as your opponents at showdown",
				"STR_QUEST_DESC_108102":"Win 2 hand with HIGH CARD at showdown",
				"STR_QUEST_DESC_108202":"Win 2 hand with A PAIR at showdown",
				"STR_QUEST_DESC_108302":"Win 2 hand with TWO PAIRS at showdown",
				"STR_QUEST_DESC_108402":"Win 2 hand with 3 OF A KIND at showdown",
				"STR_QUEST_DESC_108502":"Win 2 hand with STRAIGHT at showdown",
				"STR_QUEST_DESC_108602":"Win 2 hand with FLUSH at showdown",
				"STR_QUEST_DESC_108702":"Win 2 hand with a FULL HOUSE at showdown",
				"STR_QUEST_DESC_109102":"Interact with others for 50 times",
				"STR_QUEST_DESC_110102":"Comment on others' photos for 25 times",
				"STR_QUEST_DESC_101103":"Play 30 hands",
				"STR_QUEST_DESC_101203":"Play for 30 mins",
				"STR_QUEST_DESC_102103":"Win 10 hands",
				"STR_QUEST_DESC_102203":"Steal 15 pots pre-flop",
				"STR_QUEST_DESC_102303":"Win 10 hands at showdown",
				"STR_QUEST_DESC_103103":"Win a pot that it at least 5 times your bet for 5 times",
				"STR_QUEST_DESC_104103":"Win a pot and at least 3 side-pots at once for 3 times",
				"STR_QUEST_DESC_105103":"Win 15 hands after going All-In",
				"STR_QUEST_DESC_106103":"Win 3 hands with at least 5 players going All-In",
				"STR_QUEST_DESC_107103":"Win 3 pots with the same hand category as your opponents at showdown",
				"STR_QUEST_DESC_108103":"Win 3 hand with HIGH CARD at showdown",
				"STR_QUEST_DESC_108203":"Win 3 hand with A PAIR at showdown",
				"STR_QUEST_DESC_108303":"Win 3 hand with TWO PAIRS at showdown",
				"STR_QUEST_DESC_108403":"Win 3 hand with 3 OF A KIND at showdown",
				"STR_QUEST_DESC_108503":"Win 3 hand with STRAIGHT at showdown",
				"STR_QUEST_DESC_108603":"Win 3 hand with FLUSH at showdown",
				"STR_QUEST_DESC_108703":"Win 3 hand with a FULL HOUSE at showdown",
				"STR_QUEST_DESC_109103":"Interact with others for 100 times",
				"STR_QUEST_DESC_110103":"Comment on others' photos for 50 times",
				"STR_ACHIVEVMENT_DESC_201001":"Reach level 5",
				"STR_ACHIVEVMENT_DESC_201002":"Reach level 10",
				"STR_ACHIVEVMENT_DESC_201003":"Reach level 20",
				"STR_ACHIVEVMENT_DESC_201004":"Reach level 35",
				"STR_ACHIVEVMENT_DESC_201005":"Reach level 50",
				"STR_ACHIVEVMENT_DESC_202001":"Have 1 million chips",
				"STR_ACHIVEVMENT_DESC_202002":"Have 10 million chips",
				"STR_ACHIVEVMENT_DESC_202003":"Have 100 million chips",
				"STR_ACHIVEVMENT_DESC_202004":"Have 1 billion chips",
				"STR_ACHIVEVMENT_DESC_202005":"Have 10 billion chips",
				"STR_ACHIVEVMENT_DESC_203001":"Play 50 hands",
				"STR_ACHIVEVMENT_DESC_203002":"Play 500 hands",
				"STR_ACHIVEVMENT_DESC_203003":"Play 2500 hands",
				"STR_ACHIVEVMENT_DESC_203004":"Play 10000 hands",
				"STR_ACHIVEVMENT_DESC_203005":"Play 25000 hands",
				"STR_ACHIVEVMENT_DESC_203006":"Play 50000 hands",
				"STR_ACHIVEVMENT_DESC_203007":"Play 100000 hands",
				"STR_ACHIVEVMENT_DESC_204001":"Win 10 hands",
				"STR_ACHIVEVMENT_DESC_204002":"Win 100 hands",
				"STR_ACHIVEVMENT_DESC_204003":"Win 500 hands",
				"STR_ACHIVEVMENT_DESC_204004":"Win 2000 hands",
				"STR_ACHIVEVMENT_DESC_204005":"Win 5000 hands",
				"STR_ACHIVEVMENT_DESC_204006":"Win 10000 hands",
				"STR_ACHIVEVMENT_DESC_204007":"Win 20000 hands",
				"STR_ACHIVEVMENT_DESC_205001":"Steal 5 pots pre-flop",
				"STR_ACHIVEVMENT_DESC_205002":"Steal 50 pots pre-flop",
				"STR_ACHIVEVMENT_DESC_205003":"Steal 500 pots pre-flop",
				"STR_ACHIVEVMENT_DESC_205004":"Steal 2500 pots pre-flop",
				"STR_ACHIVEVMENT_DESC_205005":"Steal 10000 pots pre-flop",
				"STR_ACHIVEVMENT_DESC_206001":"Win 5 hands after going All-In",
				"STR_ACHIVEVMENT_DESC_206002":"Win 50 hands after going All-In",
				"STR_ACHIVEVMENT_DESC_206003":"Win 500 hands after going All-In",
				"STR_ACHIVEVMENT_DESC_206004":"Win 2500 hands after going All-In",
				"STR_ACHIVEVMENT_DESC_206005":"Win 10000 hands after going All-In",
				"STR_ACHIVEVMENT_DESC_207001":"Win 5 hands with HIGH CARD at showdown",
				"STR_ACHIVEVMENT_DESC_207002":"Win 50 hands with HIGH CARD at showdown",
				"STR_ACHIVEVMENT_DESC_207003":"Win 250 hands with HIGH CARD at showdown",
				"STR_ACHIVEVMENT_DESC_207004":"Win 1000 hands with HIGH CARD at showdown",
				"STR_ACHIVEVMENT_DESC_207005":"Win 3000 hands with HIGH CARD at showdown",
				"STR_ACHIVEVMENT_DESC_208001":"Win 5 hands with A PAIR at showdown",
				"STR_ACHIVEVMENT_DESC_208002":"Win 50 hands with A PAIR at showdown",
				"STR_ACHIVEVMENT_DESC_208003":"Win 500 hands with A PAIR at showdown",
				"STR_ACHIVEVMENT_DESC_208004":"Win 2000 hands with A PAIR at showdown",
				"STR_ACHIVEVMENT_DESC_208005":"Win 5000 hands with A PAIR at showdown",
				"STR_ACHIVEVMENT_DESC_209001":"Win 5 hands with TWO PAIRS at showdown",
				"STR_ACHIVEVMENT_DESC_209002":"Win 50 hands with TWO PAIRS at showdown",
				"STR_ACHIVEVMENT_DESC_209003":"Win 500 hands with TWO PAIRS at showdown",
				"STR_ACHIVEVMENT_DESC_209004":"Win 2000 hands with TWO PAIRS at showdown",
				"STR_ACHIVEVMENT_DESC_209005":"Win 5000 hands with TWO PAIRS at showdown",
				"STR_ACHIVEVMENT_DESC_210001":"Win 5 hands with 3 OF A KIND at showdown",
				"STR_ACHIVEVMENT_DESC_210002":"Win 50 hands with 3 OF A KIND at showdown",
				"STR_ACHIVEVMENT_DESC_210003":"Win 500 hands with 3 OF A KIND at showdown",
				"STR_ACHIVEVMENT_DESC_210004":"Win 2000 hands with 3 OF A KIND at showdown",
				"STR_ACHIVEVMENT_DESC_210005":"Win 5000 hands with 3 OF A KIND at showdown",
				"STR_ACHIVEVMENT_DESC_211001":"Win 5 hands with STRAIGHT at showdown",
				"STR_ACHIVEVMENT_DESC_211002":"Win 50 hands with STRAIGHT at showdown",
				"STR_ACHIVEVMENT_DESC_211003":"Win 500 hands with STRAIGHT at showdown",
				"STR_ACHIVEVMENT_DESC_211004":"Win 2000 hands with STRAIGHT at showdown",
				"STR_ACHIVEVMENT_DESC_211005":"Win 5000 hands with STRAIGHT at showdown",
				"STR_ACHIVEVMENT_DESC_212001":"Win 5 hands with FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_212002":"Win 50 hands with FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_212003":"Win 250 hands with FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_212004":"Win 1000 hands with FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_212005":"Win 3000 hands with FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_213001":"Win 3 hands with FULL HOUSE at showdown",
				"STR_ACHIVEVMENT_DESC_213002":"Win 30 hands with FULL HOUSE at showdown",
				"STR_ACHIVEVMENT_DESC_213003":"Win 200 hands with FULL HOUSE at showdown",
				"STR_ACHIVEVMENT_DESC_213004":"Win 500 hands with FULL HOUSE at showdown",
				"STR_ACHIVEVMENT_DESC_213005":"Win 1000 hands with FULL HOUSE at showdown",
				"STR_ACHIVEVMENT_DESC_214001":"Win 2 hands with 4 OF A KIND at showdown",
				"STR_ACHIVEVMENT_DESC_214002":"Win 10 hands with 4 OF A KIND at showdown",
				"STR_ACHIVEVMENT_DESC_214003":"Win 50 hands with 4 OF A KIND at showdown",
				"STR_ACHIVEVMENT_DESC_214004":"Win 200 hands with 4 OF A KIND at showdown",
				"STR_ACHIVEVMENT_DESC_214005":"Win 500 hands with 4 OF A KIND at showdown",
				"STR_ACHIVEVMENT_DESC_215001":"Get all 4 OF A KIND (from 2 to A)",
				"STR_ACHIVEVMENT_DESC_216001":"Win 1 hand with STRAIGHT FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_216002":"Win 5 hands with STRAIGHT FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_216003":"Win 20 hands with STRAIGHT FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_216004":"Win 50 hands with STRAIGHT FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_216005":"Win 100 hands with STRAIGHT FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_217001":"Win 1 hand with ROYAL STRAIGHT FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_217002":"Win 2 hands with ROYAL STRAIGHT FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_217003":"Win 5 hands with ROYAL STRAIGHT FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_217004":"Win 10 hands with ROYAL STRAIGHT FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_217005":"Win 20 hands with ROYAL STRAIGHT FLUSH at showdown",
				"STR_ACHIVEVMENT_DESC_218001":"Get all ROYAL STRAIGHT FLUSH (spade,heart,club,diamond)",
				"STR_ACHIVEVMENT_DESC_219001":"Use voice for 20 times",
				"STR_ACHIVEVMENT_DESC_219002":"Use voice for 100 times",
				"STR_ACHIVEVMENT_DESC_219003":"Use voice for 500 times",
				"STR_ACHIVEVMENT_DESC_219004":"Use voice for 2500 times",
				"STR_ACHIVEVMENT_DESC_219005":"Use voice for 10000 times",
				"STR_ACHIVEVMENT_DESC_220001":"Use emoji for 50 times",
				"STR_ACHIVEVMENT_DESC_220002":"Use emoji for 250 times",
				"STR_ACHIVEVMENT_DESC_220003":"Use emoji for 1000 times",
				"STR_ACHIVEVMENT_DESC_220004":"Use emoji for 5000 times",
				"STR_ACHIVEVMENT_DESC_220005":"Use emoji for 20000 times",
				"STR_ACHIVEVMENT_DESC_221001":"Get 5 friends",
				"STR_ACHIVEVMENT_DESC_221002":"Get 20 friends",
				"STR_ACHIVEVMENT_DESC_221003":"Get 50 friends",
				"STR_ACHIVEVMENT_DESC_222001":"Upload 1 photo",
				"STR_ACHIVEVMENT_DESC_222002":"Upload 10 photos",
				"STR_ACHIVEVMENT_DESC_222003":"Upload 100 photos",
				"STR_ACHIVEVMENT_DESC_223001":"Receive 5 \"Like\"",
				"STR_ACHIVEVMENT_DESC_223002":"Receive 50 \"Like\"",
				"STR_ACHIVEVMENT_DESC_223003":"Receive 500 \"Like\"",
				"STR_ACHIVEVMENT_DESC_224001":"Give 5 \"Like\"",
				"STR_ACHIVEVMENT_DESC_224002":"Give 50 \"Like\"",
				"STR_ACHIVEVMENT_DESC_224003":"Give 500 \"Like\"",
				"STR_ACHIVEVMENT_DESC_225001":"Receive 10 comments on photos",
				"STR_ACHIVEVMENT_DESC_225002":"Receive 100 comments on photos",
				"STR_ACHIVEVMENT_DESC_225003":"Receive 1000 comments on photos",
				"STR_ACHIVEVMENT_DESC_226001":"Comment on others' photos 10 times",
				"STR_ACHIVEVMENT_DESC_226002":"Comment on others' photos 100 times",
				"STR_ACHIVEVMENT_DESC_226003":"Comment on others' photos 1000 times",
				"STR_ACHIVEVMENT_DESC_227001":"Complete 5 quests",
				"STR_ACHIVEVMENT_DESC_227002":"Complete 50 quests",
				"STR_ACHIVEVMENT_DESC_227003":"Complete 500 quests",
				"STR_ACHIVEVMENT_DESC_227004":"Complete 2500 quests",
				"STR_ACHIVEVMENT_DESC_227005":"Complete 10000 quests",
				"STR_ACHIVEVMENT_DESC_228001":"Exchange items for 5 times",
				"STR_ACHIVEVMENT_DESC_228002":"Exchange items for 50 times",
				"STR_ACHIVEVMENT_DESC_228003":"Exchange items for 500 times",
				"STR_ACHIVEVMENT_DESC_229001":"Give chips to other players in-game for 10 times",
				"STR_ACHIVEVMENT_DESC_229002":"Give chips to other players in-game for 100 times",
				"STR_ACHIVEVMENT_DESC_229003":"Give chips to other players in-game for 1000 times",
				"STR_ACHIVEVMENT_DESC_230001":"Give free chips to your friends for 10 times",
				"STR_ACHIVEVMENT_DESC_230002":"Give free chips to your friends for 100 times",
				"STR_ACHIVEVMENT_DESC_230003":"Give free chips to your friends for 1000 times",
				"STR_ACHIVEVMENT_DESC_231001":"Get 100000 free chips",
				"STR_ACHIVEVMENT_DESC_231002":"Get 250000 free chips",
				"STR_ACHIVEVMENT_DESC_231003":"Get 1 million free chips",
				"STR_ACHIVEVMENT_DESC_232001":"Login to the game 5 days in total",
				"STR_ACHIVEVMENT_DESC_232002":"Login to the game 25 days in total",
				"STR_ACHIVEVMENT_DESC_232003":"Login to the game 100 days in total",
				"STR_ACHIVEVMENT_DESC_232004":"Login to the game 250 days in total",
				"STR_ACHIVEVMENT_DESC_232005":"Login to the game 500 days in total",
				"STR_LOGIN_VERSION":"Version:",
				"STR_INFORMATION_PERSONAL_SIGNATURE_DEFAULT":"Leave visitors a message by adding a personal signature.",
				"STR_MESS_EVALUATION_TITLE":"Thanks for Your Rating",
				"STR_MESS_EVALUATION_CONTENT":"Due to your support and rating of our game, %d free chips has been sent in this Message. Please get it through clicking the wallet in the bottom right corner.",
    
};
