 module.exports = {
				"STR_COREPLAY_BUTTON_FOLD":"หมอบ",
				"STR_COREPLAY_BUTTON_CHECK":"ผ่าน",
				"STR_COREPLAY_BUTTON_CALL":"สู้%s",
				"STR_COREPLAY_BUTTON_RAISE":"เกทับ",
				"STR_COREPLAY_BUTTON_CONFIRM":"",
				"STR_COREPLAY_BUTTON_ALLIN":"All In",
				"STR_COREPLAY_BUTTON_PREP_CHECKORFOLD":"ผ่าน/หมอบ",
				"STR_COREPLAY_BUTTON_PREP_AUTOCHECK":"ผ่าน",
				"STR_COREPLAY_BUTTON_PREP_CALL":"สู้%s",
				"STR_COREPLAY_BUTTON_PREP_CALLANY":"สู้อัตโนมัติ",
				"STR_INFORMATION_TILLE_1":"ข้อมูลส่วนตัว",
				"STR_INFORMATION_TILLE_2":"รายการไอเทม",
				"STR_INFORMATION_TILLE_3":"ข้อความสำเร็จรูป",
				"STR_INFORMATION_TILLE_4":"เสียงสำเร็จรูป",
				"STR_INFORMATION_TILLE_5":"ข้อมูลสถิติ",
				"STR_INFORMATION_PERSONAL_LV":"Lv.",
				"STR_INFORMATION_PERSONAL_ID":"ID",
				"STR_INFORMATION_PERSONAL_NAME":"ชื่อ",
				"STR_INFORMATION_PERSONAL_MALE":"ชาย",
				"STR_INFORMATION_PERSONAL_FEMALE":"หญิง",
				"STR_INFORMATION_PERSONAL_ADDRESS":"ที่อยู่：",
				"STR_INFORMATION_PERSONAL_ADDRESS_NULL":"ไม่ทราบ",
				"STR_INFORMATION_PERSONAL_SIGNATURE":"เซ็นชื่อ：",
				"STR_INFORMATION_PERSONAL_PHOTO_DEFAULT":"อัพโหลดใหม่ 1รูป",
				"STR_INFORMATION_PERSONAL_PHOTO_INREVIEW":"ตรวจสอบอยู่",
				"STR_INFORMATION_ITEMLIST_TIME":"วัน",
				"STR_INFORMATION_ITEMLIST_TIME_HOUR":"ชม.",
				"STR_INFORMATION_QUICKCHAT_WORDS":"",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_1":"เกมส์เริ่มแล้ว ฉันพร้อมชนะแล้วนะ",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_2":"อย่าช้าสิ รีบลงเดิมพันหน่อย",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_3":"ไพ่ในมือดีมากๆ ดูเหมือนรอบนี้ฉันจะชนะแล้ว",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_4":"ฉันall in กลัวก็หมอบไพ่ไปนะ",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_5":"แม้ว่ารอบนี้ฉันชนะแล้ว แต่ฉันก็ไม่ปราณีหรอกนะ",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_6":"หมอบก็ไม่ได้แสดงว่าฉันแพ้นะ ฉันแค่อยากพัก",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_7":"คุณเล่นไพ่ได้ดีมาก จนฉันอยากยกนิ้วให้เลย",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_8":"ถึงแม้จะมีเรื่องแบบนี้ แต่อย่าไปเชื่อ",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_9":"รอบนี้ฉันไม่ได้จริงจัง ครั้งหน้าไม่แพ้แน่",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_10":"ฉันยอมออกไปแล้ว พวกเธอก็โชคดีนะ",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_NULL":"กดตรงนี้กรอกข้อความสำเร็จรูปของคุณ",
				"STR_INFORMATION_QUICKCHAT_VOICE":"",
				"STR_INFORMATION_QUICKCHAT_VOICE_DEFAULT":"กดค้างตรงนี้บันทึกเสียง",
				"STR_INFORMATION_QUICKCHAT_VOICE_ENTERTITLE":"กดตรงนี้กรอกหัวเรื่อง",
				"STR_INFORMATION_QUICKCHAT_VOICE_RECORDING":"กำลังบันทึกเสียง",
				"STR_INFORMATION_STATISTICS_ID":"ID:",
				"STR_INFORMATION_STATISTICS_GAMES":"จำนวนรอบไพ่:",
				"STR_INFORMATION_STATISTICS_WINS":"จำนวนรอบชนะ:",
				"STR_INFORMATION_STATISTICS_LOSE":"จำนวนรอบแพ้:",
				"STR_INFORMATION_STATISTICS_WINRATE":"อัตราชนะ:",
				"STR_INFORMATION_STATISTICS_SHOWINRIVER":"อัตราเปิดไพ่:",
				"STR_INFORMATION_STATISTICS_FOLDINPREFLOP":"อัตราหมอบ：",
				"STR_INFORMATION_STATISTICS_ALLININPREFLOP":"อัตราall inหลังแจกไพ่：",
				"STR_INFORMATION_STATISTICS_HIGHESTCHIP":"ประวัติชิปมากสุด:",
				"STR_INFORMATION_STATISTICS_MOSTWIN":"ชนะมากสุด:",
				"STR_INFORMATION_STATISTICS_BESTCARDS":"รูปแบบไพ่ใหญ่สุด:",
				"STR_INFORMATION_STATISTICS_GIVECHIPTOFRIEND":"จำนวนครั้งส่งชิปฟรีให้เพื่อน:",
				"STR_INFORMATION_STATISTICS_GIVECHIPTOFRIEND_TIMES":"ครั้ง",
				"STR_INFORMATION_STATISTICS_GIVECHIPINGAME":"จำนวนครั้งส่งชิปให้ผู้เล่น:",
				"STR_INFORMATION_STATISTICS_GIVECHIPINGAME_TIMES":"ครั้ง",
				"STR_INFORMATION_ITEMLIST_ITEM_TITLE":"ที่คุณมีอยู่:",
				"STR_INFORMATION_ITEMLIST_PATCH_TITLE":"คุณสามารถแลกได้:",
				"STR_RANKING_TITLE_MAIN":"แรงกิ้งค์",
				"STR_RANKING_TITLE_1":"ชิปรวม",
				"STR_RANKING_TITLE_2":"อัตรากำไร",
				"STR_RANKING_TITLE_3":"ได้รับชิปวันนี้",
				"STR_RANKING_TITLE_4":"ชนะวันนี้",
				"STR_RANKING_TITLE_5":"ปฎิสัมพันธ์",
				"STR_RANKING_GMT_GMT":"เวลาGMT",
				"STR_RANKING_GMT_EXPLAIN":"เกมส์ใช้เวลาตามGMTเป็นมาตรฐาน ที่นี้แสดงเวลาแบบGMT ผู้เล่นทุกท่านโปรดทราบ",
				"STR_RANKING_TOP_TOP":"แถวหน้า",
				"STR_RANKING_RANKING_NOPLAYER":"แรงกิ้งค์ยังไม่มีผู้เล่น",
				"STR_CHAT_EXPRESSION_TITLE":"อิโมจิแสดงสีหน้า",
				"STR_CHAT_QUICKWORDS_TITLE":"ข้อความสำเร็จรูป",
				"STR_CHAT_QUICKVOICES_TITLE":"เสียงสำเร็จรูป",
				"STR_CHAT_INPUT_DEFAULT":"กดตรงนี้กรอกตัวอักษร",
				"STR_CHAT_INPUT_DEFAULT_IOS":"กดตรงนี้กรอกตัวอักษร",
				"STR_CHAT_QUICKVOICE_NOVICE":"",
				"STR_CHAT_QUICKVOICE_NOTITLE":"ยังไม่ได้กรอกคำบรรยาย",
				"STR_TABLEBOARD_CAHT_NOQUICKVOICE":"ตอนนี้คุณยังไม่มีเสียงสำเร็จรูปที่บันทึกไว้",
				"STR_TABLEBOARD_CHAT_NOQUICKTEXT":"ตอนนี้คุณยังไม่มีข้อความสำเร็จรูปที่บันทึกไว้",
				"STR_TABLEBOARD_RECORDING_COUNTDOWN":"เหลือ%dวินาที",
				"STR_FRIENDS_TITLE":"เพื่อนของคุณ",
				"STR_FRIENDS_NOFRIENDS":"ตอนนี้คุณยังไม่มีเพื่อน กดปุ่มค้นหาที่บนมุมขวา คุณสามารถใช้ชื่อผู้เล่นหาผู้เล่นที่สอดคล้อง ที่หน้าหลักโต๊ะเกมส์และหน้าหลักเกมส์ กดที่รูปโปรไฟต์ผู้เล่น กดปุ่มเพิ่มเป็นเพื่อน ก็จะส่งคำขอได้ง่ายๆ รีบมาลองดูนะ",
				"STR_FRIENDS_FRIENDS_UPDATE":"แสดงรูปภาพล่าสุดของเพื่อนก่อน",
				"STR_FRIENDS_FRIENDS_OL":"แสดงเพื่อนที่ออนไลน์อยู่ก่อน",
				"STR_FRIENDS_FRIENDS_ACTIVE":"แสดงเพื่อนที่ใช้งานอยู่ก่อน",
				"STR_FRIENDS_FRIENDS_MAX":"MAX",
				"STR_FRIENDS_FRIENDS_INFORMATION_LV":"Lv.",
				"STR_FRIENDS_FRIENDS_INFORMATION_MALE":"ชาย",
				"STR_FRIENDS_FRIENDS_INFORMATION_FEMALE":"หญิง",
				"STR_FRIENDS_FRIENDS_INFORMATION_ADDRESS":"ที่อยู่：",
				"STR_FRIENDS_FRIENDS_INFORMATION_DEFAULT":"แสดงจำนวนการส่งไลก์ คอนเม้นต์และส่งชิปฟรีให้ผู้เล่นคนนี้แล้วเท่าไหร่",
				"STR_FRIENDS_FRIENDS_INFORMATION_NOPHOTO":"ผู้เล่นคนนี้ไม่ได้อัพโหลดรูปใดๆ เลย",
				"STR_FRIENDS_FRIENDS_INFORMATION_GAMES":"เกมส์",
				"STR_FRIENDS_FRIENDS_INFORMATION_WIN":"ชนะ ",
				"STR_FRIENDS_FRIENDS_INFORMATION_LOSE":"แพ้",
				"STR_FRIENDS_FRIENDS_INFORMATION_WINRATE":"อัตราชนะ:",
				"STR_FRIENDS_FRIENDS_INFORMATION_SHOWINRIVER":"อัตราเปิดไพ่:",
				"STR_FRIENDS_FRIENDS_INFORMATION_FOLDINPREFLOP":"อัตราหมอบ：",
				"STR_FRIENDS_FRIENDS_INFORMATION_ALLININPREFLOP":"อัตราall inหลังแจกไพ่:",
				"STR_FRIENDS_FRIENDS_INFORMATION_HIGHESTCHIP":"ประวัติชิปมากสุด:",
				"STR_FRIENDS_FRIENDS_INFORMATION_MOSTWIN":"ชนะมากสุด:",
				"STR_FRIENDS_FRIENDS_INFORMATION_BESTCARDS":"รูปแบบไพ่ใหญ่สุด:",
				"STR_FRIENDS_FRIENDS_SEARCHTITLE":"เพื่อนที่ค้นหาพบ",
				"STR_FRIENDS_FRIENDS_SEARCHTIPS":"กรุณากรอกอย่างน้อย4ตัวอักษร เพื่อค้นหาชื่อ",
				"STR_FRIENDS_FRIENDS_SEARCH":"ตามชื่อผู้เล่นพบแล้ว %dคน แสดงผู้เล่นคล้ายกันมากสุด %dคน",
				"STR_LOGIN_PHONELOGIN":"โทรศัพท์",
				"STR_LOGIN_ACCOUNTLOGIN":"บัญชี",
				"STR_LOGIN_FACEBOOKLOGIN":"Facebook",
				"STR_LOGIN_GUESTLOGIN":"นักท่องเที่ยว",
				"STR_LOGIN_ACCOUNTLOGIN_ACCOUNT":"กรอกอีเมลของคุณ",
				"STR_LOGIN_ACCOUNTLOGIN_PASSWORD":"กรอกรหัสผ่านของคุณ",
				"STR_LOGIN_ACCOUNTLOGIN_AUTOLOGIN":"ล็อกอินอัตโนมัต",
				"STR_LOGIN_ACCOUNTLOGIN_RETRIEVEPASSWORD":"กู้คืนรหัสผ่าน",
				"STR_LOGIN_ACCOUNTLOGIN_LOGIN":"ล็อกอิน",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTER":"ลงทะเบียน",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTERACCOUNT":"กรุณากรอกอีเมลของคุณ",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTERENTERPASSWORD":"กรุณากรอกรหัสผ่านของคุณ",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTERCONFRIMPASSWORD":"กรุณายืนยันรหัสผ่าน",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTERREGISTER":"ลงทะเบียน",
				"STR_LOGIN_ACCOUNTLOGIN_RETRIEVEPASSWORD_EXPLAIN":"หากคุณต้องการกู้คืนรหัสผ่าน กรุณากรอกอีเมลที่ใช้ลงทะเบียนแล้ว เราจะส่งรหัสผ่านไปที่อีเมลนี้",
				"STR_LOGIN_ACCOUNTLOGIN_RETRIEVEPASSWORD_ENTER":"กรุณากรอกอีเมลที่ลงทะเบียนของคุณ",
				"STR_LOGIN_ACCOUNTLOGIN_RETRIEVEPASSWORD_SENDEMAIL":"ส่งอีเมล",
				"STR_LOGIN_TERMSOFSERVICE":"ข้อตกลงผู้ใช้",
				"STR_LOBBY_TITLE":"ห้อง",
				"STR_LOBBY_ID":"ห้องID",
				"STR_LOBBY_BLIND":"บลายด์ %s/%s",
				"STR_LOBBY_5PLAYERS":"ห้อง5คน",
				"STR_LOBBY_9PLAYERS":"ห้อง9คน",
				"STR_LOBBY_FULL":"ห้องเต็ม",
				"STR_LOBBY_EMPTY":"ห้องว่าง",
				"STR_SIT_ROOMID":"ห้องID %d",
				"STR_SIT_BLIND":"บิ๊ก/สมอลบลายด์ %s/%s",
				"STR_SIT_MINBLIND":"นำเข้าน้อยสุด",
				"STR_SIT_MAXBLIND":"นำเข้ามากสุด",
				"STR_SIT_AUTOSIT":"เมื่อชิปไม่พอนำชิปเข้าอัตโนมัตพร้อมทั้งนั่งลง",
				"STR_SIT_LEAVE":"",
				"STR_SIT_SIT":"นั่งลง",
				"STR_SIT_NOCHIP":"ชิปไม่พอ",
				"STR_SIT_SHOP":"ห้าง",
				"STR_INVITE_TITLE":"เล่นกับเพื่อนของคุณ",
				"STR_INVITE_BUTTON":"เชิญมาที่ห้องเกมส์",
				"STR_INVITE_NOFRIEND":"เสียใจด้วย คุณยังไม่มีเพื่อน รีบไปเป็นเพื่อนกับผู้เล่นคนอื่นเร็ว",
				"STR_INVITE_UNKNOWN":"ที่อยู่     ไม่ทราบ",
				"STR_MES_FRIEND_TITLE":"ข้อมูลเพื่อน",
				"STR_MES_SYSTEM_TITLE":"ข้อมูลระบบ",
				"STR_MES_ADDFRIEND_RCCEIVE":"%s ต้องการเป็นเพื่อนกับคุณ คุณต้องการยินยอมไหม？",
				"STR_MES_ADDFRIEND_AGREE":"ยินดีด้วย！%sยอมรับคำร้องขอเป็นเพื่อนของคุณแล้ว คุณสามารถหาเขาได้ที่หน้าหลักเพื่อน\n",
				"STR_MES_ADDFRIEND_YOUAGREE":" คุณยอมรับคำร้องขอเป็นเพื่อนของ%sแล้ว คุณสามารถหาเขาได้ที่หน้าหลักเพื่อน\n",
				"STR_MES_CHIPS_GIVE":"%sส่ง %dชิปฟรีให้คุณ รีบมารับเร็ว",
				"STR_MES_CHIPS_RECEIVE":"คุณรับ %dชิปฟรี ที่มาจาก%s ",
				"STR_MES_MESSAGE_NULL":"ตอนนี้ยังไม่มีข้อมูล",
				"STR_MES_MONTH_JAN":"ม.ค.",
				"STR_MES_MONTH_FEB":"ก.พ.",
				"STR_MES_MONTH_MAR":"มี.ค.",
				"STR_MES_MONTH_APR":"เม.ย.",
				"STR_MES_MONTH_MAY":"พ.ค.",
				"STR_MES_MONTH_JUN":"มิ.ย.",
				"STR_MES_MONTH_JUL":"ก.ค.",
				"STR_MES_MONTH_AUG":"ส.ค.",
				"STR_MES_MONTH_SEP":"ก.ย.",
				"STR_MES_MONTH_OCT":"ต.ค.",
				"STR_MES_MONTH_NOV":"พ.ย.",
				"STR_MES_MONTH_DEC":"ธ.ค.",
				"STR_HOMESCREEN_OLPLAYER":" ผู้เล่นออนไลน์:%s",
				"STR_HOMESCREEN_PHOTOUPLOAD":"เพื่อนของคุณ %s อัพเดทรูปภาพใหม่แล้ว",
				"STR_HOMESCREEN_NOUPLOAD":" ยังไม่มีเพื่อนอัพเดทรูปภาพใหม่",
				"STR_EVENT_BACK":"กลับ",
				"STR_ANNOUNCEMENT_TITLE":"ประกาศ",
				"STR_PLAYER_INF_NAME":"",
				"STR_PLAYER_INF_TITLE_PHOTO":"รูปภาพ",
				"STR_PLAYER_INF_TITLE_ACHIEVEMENTS":"ผลงาน",
				"STR_PLAYER_INF_LV":"Lv.",
				"STR_PLAYER_INF_MALE":"ชาย",
				"STR_PLAYER_INF_FEMALE":"หญิง",
				"STR_PLAYER_INF_ADDRESS":"ที่อยู่",
				"STR_PLAYER_INF_BUTTON_BLOCK":"กดตรงนี้บล็อกผู้เล่น",
				"STR_PLAYER_INF_BLOCKBUTTON":"บล็อก",
				"STR_PLAYER_INF_BUTTON_UNLOCK":"",
				"STR_PLAYER_INF_UNLOCKBUTTON":"ปลดบล็อก",
				"STR_PLAYER_INF_BUTTON_REPORT":"กดตรงนี้รายงานรูปโปรไฟต์ผู้เล่น",
				"STR_PLAYER_INF_REPORTBUTTON":"รายงาน",
				"STR_PLAYER_INF_BLOCK":"หลังจากบล็อกแล้ว คุณจะไม่สามารถได้รับข้อความ เสียง หรืออิโมจิที่มาจากผู้เล่นคนนี้อีก คุณแน่ใจหรือไม่ว่าจะบล็อกผู้เล่นคนนี้？",
				"STR_PLAYER_INF_UNBLOCK":"หลังจากปลดบล็อกผู้เล่นคนนี้แล้ว คุณสามารถได้รับข้อความ เสียง หรืออิโมจิที่มาจากผู้เล่นคนนี้ได้อีกครั้ง",
				"STR_PLAYER_INF_REPORT":"หลังจากมีผู้เล่นจำนวนมากรายงานรูปโปรไฟต์นี้ รูปโปรไฟต์นี้จะถูกบล็อก เราจะรีบดำเนินการตรวจสอบโดยเร็ว คุณแน่ใจหรือไม่ว่าจะรายงานรูปโปรไฟต์นี้？",
				"STR_PLAYER_PHOTO_NULL":"ผู้เล่นคนนี้ไม่ได้อัพโหลดรูปใดๆ เลย",
				"STR_CHECKPHOTO_NOAUTHORITY":"ขออภัย เนื่องจากการตั้งค่าของผู้เล่นคนนี้ คุณไม่มีสิทธิ์ตรวจเช็ครูปของผู้เล่นคนนี้",
				"STR_PLAYER_PHOTO_CRITICTITLE":"คอมเม้นต์",
				"STR_PLAYER_STATISTICS_GAMES":"จำนวนรอบไพ่:",
				"STR_PLAYER_STATISTICS_WINS":"ชนะ",
				"STR_PLAYER_STATISTICS_LOSE":"แพ้",
				"STR_PLAYER_STATISTICS_WINRATE":"อัตราชนะ:",
				"STR_PLAYER_STATISTICS_SHOWINRIVER":"อัตราเปิดไพ่:",
				"STR_PLAYER_STATISTICS_FOLDINPREFLOP":"อัตราหมอบ：",
				"STR_PLAYER_STATISTICS_ALLININPREFLOP":"อัตราall inหลังแจกไพ่：",
				"STR_PLAYER_STATISTICS_HIGHESTCHIPS":"ประวัติชิปมากสุด:",
				"STR_PLAYER_STATISTICS_MOSTWIN":"ชนะมากสุด:",
				"STR_PLAYER_STATISTICS_BTESTCARD":"รูปแบบไพ่ใหญ่สุด:",
				"STR_PLAYER_STATISTICS_MINS":"%s นาที",
				"STR_PLAYER_ACHIEVEMENT_NULL":"ผู้เล่นคนนี้ยังไม่ได้รับผลงานใดๆ เลย",
				"STR_LOGINREWARD_TITLE":"รางวัลล็อกอินต่อเนื่อง",
				"STR_LOGINREWARD_DAY":"วันที่%d",
				"STR_LOGINREWARD_RECEIVED":"รับแล้ว",
				"STR_LOGINREWARD_TIPS":"หากคุณรักษาการล็อกอินต่อนเนื่องไว้ คุณจะได้รับรางวัลมากยิ่งขึ้น",
				"STR_LOGINREWARD_SUCCESS":"",
				"STR_ABOUTUS_STAFF":"Poker Royal Texas Hold'em Staff List\n\n\nGameDesinger\n\nStone\nJohn Smith\n\n\nProgrammer\n\nJack\nWillian\nHaven \nSpiro\nBob\nRussell\n\n\nArtDesinger\n\nPantheon\nEmma\nMandy\n\n\nGameTester\n\nJoffence\nDoris\n\n\nSpecial Thanks\n\nChris\nAlex\nMatata\nBlank",
				"STR_BUTTON_YES":"ใช่",
				"STR_BUTTON_NO":"ไม่ใช่",
				"STR_BUTTON_OK":"ยืนยัน",
				"STR_BUTTON_IGNORE":"",
				"STR_BUTTON_AGREE":"ตกลง",
				"STR_OPTIONS_TITLE":"ตั้งค่า",
				"STR_OPTIONS_VOICE":"เสียง",
				"STR_OPTIONS_SOUND":"เสียงซาวด์",
				"STR_OPTIONS_AUTOSIT":"นั่งอัตโนมัต",
				"STR_OPTIONS_VIBRATION":"สั่น",
				"STR_OPTIONS_FOLLOW":"ยินยอมให้ผู้เล่นติดตาม",
				"STR_OPTIONS_INVITE":"รับข้อมูลการเชิญ",
				"STR_OPTIONS_SEEPHOTOS":"ใครสามารถดูรูปของฉันได้",
				"STR_OPTIONS_CHOSEN_YES":"ใช่",
				"STR_OPTIONS_CHOSEN_NO":"ไม่ใช่",
				"STR_OPTIONS_SEEPHOTOS_FRIEND":"เฉพาะเพื่อนที่ดูได้",
				"STR_OPTIONS_SEEPHOTOS_NOONE":"ทุกคนไม่สามารถดูได้",
				"STR_OPTIONS_SEEPHOTOS_ANYONE":"ทุกคนสามารถดูได้",
				"STR_OPTIONS_RATE":"ให้คะแนนเกมส์",
				"STR_OPTIONS_CACHE":"ล้างแคช",
				"STR_OPTIONS_CACHE_CONFIRM":"ล้างแคชจะลบรูปโปรไฟต์ รูปภาพที่คุณได้โหลดแล้ว คุณแน่ใจหรือไม่ว่าจะล้างแคช？",
				"STR_OPTIONS_CACHE_CLEARED":"ล้างแคชสำเร็จ",
				"STR_OPTIONS_ABOUT":"เกี่ยวกับเรา",
				"STR_OPTIONS_REPORT":"รายงานปัญหา",
				"STR_OPTIONS_FOLLOWUS":"ติดตามเรา",
				"STR_OPTIONS_CONTACT":"ติดต่อเรา",
				"STR_LOADING_1":"นำเพื่อนมาที่เกมส์ แต่ก็อย่าลืมว่าในความเป็นจริงก็เล่นด้วยอยู่",
				"STR_LOADING_2":"สื่อสารกับคนอื่นกรุณารักษามารยาท ในขณะที่เคารพผู้อื่นนั้น คุณก็จะได้รับการเคารพจากคนอื่นเช่นกัน",
				"STR_LOADING_3":"ในห้องเกมส์อย่าได้ลวนลามเจ้ามือ แม้ว่าพวกเขาจะหล่อหรือเซ็กซี่มากก็ตาม",
				"STR_LOADING_4":"หากอยู่ในเกมส์ได้รับความล้มเหลวขัดข้อง ไม่ต้องท้อไป ชีวิตไม่ได้ทอดทิ้งคุณ",
				"STR_LOADING_5":"ทำเรื่องอะไรก็ตามต้องการระดับความเหมาะสม รวมทั้งการเล่นโป๊กเกอร์รอยัล",
				"STR_LOADING_6":"กรุณาอย่าลืมเปิดข้อมูลเพื่อนทุกวัน กดปุ่มส่งชิปส่งชิปฟรีให้เพื่อน",
				"STR_LOADING_7":"เมื่อถึงรอบคุณแล้ว กดชิปด้านล่างซ้าย ก็สามารถเลือกจำนวนเงินเกทับแบบเร็วได้",
				"STR_LOADING_8":"ตอนที่ตรวจเช็คข้อมูลผู้เล่น กดที่รูปโปรไฟต์อีกครั้ง ก็สามารถบล็อกผู้เล่นน่ารำคาญได้",
				"STR_LOADING_9":"หากต้องการคุยกันส่วนตัว กรุณาอย่าลืมใช้ปุ่มเสียงที่หน้ารายละเอียดข้อมูลผู้เล่น",
				"STR_LOADING_10":"กรุณาอย่าลืมตรวจเช็คกิจกรรมนะ ไม่แน่อาจมีเซอร์ไพรส์",
				"STR_LOADING_11":"รักษาการล็อกอินต่อเนื่อง จะได้รับรางวัลที่ดีที่สุด",
				"STR_LOADING_END":"รักษาจิตใจให้ปกติอยู่ตลอดเวลา ชนะก็ไม่ต้องตื่นเต้น แพ้ก็ไม่ต้องหดหู่ใจ",
				"STR_TABLEBOARD_ID":"ห้องID%d บิ๊ก/สมอบลายด์ %s/%s",
				"STR_CARDTYPE_HIGH_CARD":"ไพ่สูง",
				"STR_CARDTYPE_PAIR_CARD":"1คู่",
				"STR_CARDTYPE_TWO_PAIRS_CARD":"2คู่",
				"STR_CARDTYPE_THREE_CARD":"ตอง",
				"STR_CARDTYPE_STRAIGHT":"สเตรท",
				"STR_CARDTYPE_FLUSH":"ฟลัช",
				"STR_CARDTYPE_FULL_HOUSE":"ฟูลเฮ้าท์",
				"STR_CARDTYPE_FOUR_OF_A_KIND":"โฟร์การ์ด",
				"STR_CARDTYPE_STRAIGHT_FLUSH":"สเตรทฟลัช",
				"STR_CARDTYPE_ROYAL_FLUSH":"รอยัลสเตรทฟลัช",
				"STR_TABLEBOARD_EXP":"Exp.",
				"STR_QUESTS_TITLE":"ภารกิจ",
				"STR_QUESTS_RECEIVEBUTTON":"กดรับ",
				"STR_ACHIEVEMENTS_TITLE":"ผลงาน",
				"STR_LVUP_TITLE":"ยินดีด้วย！",
				"STR_LVUP_TEXT":"ยินดีด้วย คุณอัพเกรดถึงLv.%d ได้รับรางวัล %sชิปแล้ว",
				"STR_SHOP_TITLE":" ห้าง",
				"STR_SHOP_BUTTON":"ซื้อ",
				"STR_ALMS_TITLE":"ฟื้นคืนชีพ",
				"STR_ALMS_TEXT":"ผู้เล่นที่น่ารัก เนื่องจากตอนนี้จำนวนชิปและเพชรของคุณน้อยมาก ระบบส่ง %sชิปให้คุณ วันนี้คุณยังสามารถได้รับเงินสงเคราะห์อีก %dครั้ง",
				"STR_BUG_REPORT":"กดส่งคำถาม",
				"STR_BUG_INPUT":"กรุณากรอกคำถามที่คุณต้องการส่ง",
				"STR_BUG_TIP":"คำถามของคุณส่งให้เซิร์ฟเวอร์แล้ว ฝ่ายบริการลูกค้าจะเร่งแก้ไขและตอบกลับโดยเร็ว",
				"STR_BUG_TIME":"เวลาส่ง",
				"STR_BUG_WAIT":"รอฝ่ายบริการลูกค้าตอบกลับ",
				"STR_BUG_RESPONSETIME":"เวลาตอบกลับ",
				"STR_BUG_DELTIP":"คุณแน่ใจหรือไม่ว่าจะลบคำถามนี้？",
				"STR_BUG_VIEW":"ดูรายละเอียด",
				"STR_BUG_COMMIT":"ส่ง",
				"STR_BUG_DELTIPDONE":"ลบสำเร็จ",
				"STR_BUG_DELTIPFAIL":"ลบล้มเหลว",
				"STR_BUG_COMMIT_TIP":"ส่งล้มเหลว",
				"STR_POKER_ROOM_BET":"เดิมพัน%s/%s",
				"STR_POKERTABLEBOARD_ID":"ห้องID%d น้อยสุด/มากสุด เดิมพัน%s/%s",
				"STR_POKER_PRE_BET":"เดิมพัน",
				"STR_POKER_TYPE_POK9":"ป๊อก9",
				"STR_POKER_TYPE_POK8":"ป๊อก8",
				"STR_POKER_TYPE_TONG":"ตอง",
				"STR_POKER_TYPE_SAM_LUEANG":"สามเหลือง",
				"STR_POKER_TYPE_STRAIGHT_FLUSH":"ไพ่เรียงดอก",
				"STR_POKER_TYPE_STRAIGHT":"ไพ่เรียง",
				"STR_POKER_TYPE_SCORE_0":"0แต้ม",
				"STR_POKER_TYPE_SCORE_1":"1แต้ม",
				"STR_POKER_TYPE_SCORE_2":"2แต้ม",
				"STR_POKER_TYPE_SCORE_3":"3แต้ม",
				"STR_POKER_TYPE_SCORE_4":"4แต้ม",
				"STR_POKER_TYPE_SCORE_5":"5แต้ม",
				"STR_POKER_TYPE_SCORE_6":"6แต้ม",
				"STR_POKER_TYPE_SCORE_7":"7แต้ม",
				"STR_POKER_TYPE_SCORE_8":"8แต้ม",
				"STR_POKER_TYPE_SCORE_0_9":"ไพ่นับแต้ม 0-9",
				"STR_POKER_TYPE_SCORE_9":"9แต้ม",
				"STR_POKER_INTRUUCE":"อธิบายรูปแบบไพ่",
				"STR_POKER_INTRUUCE1":"ไพ่ใหญ่น้อยดูจากบนลงล่าง",
				"STR_POKER_INTRUUCE2":"ไพ่เหล่านี้คือ 0แต้ม",
				"STR_POKER_INTRUUCE3":"ไพ่เหล่านี้คือ1-9แต้ม",
				"STR_POKER_INTRUUCE4":"ไพ่ในมือบวกรวมกัน นับแต้มแค่หลักหน่อย",
				"STR_POKER_INTRUUCE5":"ไพ่2ใบแรกคือ9แต้ม",
				"STR_POKER_INTRUUCE6":"ไพ่2ใบแรกคือ8แต้ม",
				"STR_POKER_INTRUUCE7":"KA2、A24 ไม่ใช่ไพ่เรียง",
				"STR_POKER_INTRUUCE8":"อัตราการจ่ายนับเด้ง",
				"STR_POKER_INTRUUCE9":"ไพ่ 2ใบทีมีดอกเหมือนกัน",
				"STR_POKER_INTRUUCE10":"ไพ่ 3ใบที่มีดอกเหมือนกัน （เทียบไพ่โดยดูแต้ม）",
				"STR_POKER_INTRUUCE11":"จบไพ่รอบนี้แล้ว ออกจากห้อง",
				"STR_POKER_INTRUUCE12":"หลังจากไพ่รอบนี้จบ ลุกจากที่นั่งและออกจากห้อง\n",
				"STR_WIN_STREAK":"ชนะต่อเนื่อง:",
				"STR_PLAYER":"ผู้เล่น",
				"STR_DEAR":"เจ้ามือ",
				"STR_GAME_GOTODEAR":"กดเป็นเจ้ามือ",
				"STR_CHIP_NOT_ENOUGH":"ชิปไม่เพียงพอ อย่างน้อย%s ชิป ถึงจะเป็นเจ้ามือได้ ไปที่ห้างหรือไม่？",
				"STR_POKERTABLEBOARD_ID1":"น้อยสุด/มากสุด เดิมพัน%s/%s",
				"STR_GAME_GOTODEAR_1":"เป็นเจ้ามือสำเร็จ ต้องเล่นให้ครบ 5รอบถึงจะออกได้\n",
				"STR_GAME_GOTODEAR_2":"ผู้เล่นเป็นเจ้ามือสำเร็จ",
				"STR_STATIC_BIGWIN":"ชนะมากสุด:",
				"STR_CARDTYPE100":"ไพ่ 3ใบในกลุ่ม JQK",
				"STR_CARDTYPE101":"ไพ่ 3ใบเรียงกันและมีดอกเหมือนกัน",
				"STR_CARDTYPE102":"ไพ่ 2ใบทีมีแต้มเหมือนกัน  ",
				"STR_CARDTYPE103":"ไพ่เรียง",
				"STR_CARDTYPE104":"ไพ่ 3ใบเรียงกัน ดอกไม่เหมือนกัน",
				"STR_ADDFRIEND_ONESELF":"จำนวนเพื่อนของคุณได้ถึงขีดจำกัดแล้ว คุณสามารถไปซื้อไอเทมสมุดรายชื่อได้ที่ห้าง เพื่ออัพระดับขีดจำกัดเพื่อน ",
				"STR_ADDFRIEND_OTHERS":"เสียใจด้วย จำนวนเพื่อนของฝ่ายตรงข้ามได้ถึงขีดจำกัดแล้ว ตอนนี้คุณไม่สามารถเพิ่มเขาเป็นเพื่อนได้",
				"STR_MESSRECEIVE_UNDONE":"ของรางวัลที่อยู่ในข้อมูลนี้ได้ถูกคุณกดรับแล้วเรียบร้อย",
				"STR_LOGIN_WORNING":"บัญชีของคุณถูกอายัญ หากคุณมีข้อสงสัย กรุณาส่งอีเมลมาที่ฝ่ายบริการของเรา",
				"STR_LOGIN_INFO_ERROR":"คุณกรอกบัญชีหรือรหัสผ่านไม่ถูกต้อง กรุณากรอกใหม่อีกครั้ง",
				"STR_LOGIN_INFO_NULL":"ล็อกอินบัญชีหรือรหัสผ่านไม่สามารถเว้นว่างได้ กรุณากรอกด้วย",
				"STR_LOGIN_EMALL_REGISTERED":"อีเมลที่คุณกรอกเคยถูกลงทะเบียนแล้ว กรุณากรอกอีเมลที่สามารถใช้งานได้ใหม่อีกครั้ง",
				"STR_LOGIN_EMAIL_ERROR":"คุณกรอกรูปแบบอีเมลผิดพลาด กรุณากรอกใหม่อีกครั้ง",
				"STR_LOGIN_PASSWORD_SHORT":"รหัสบัญชีอย่างน้อย6-16ตัวอักษร กรุณากรอกรหัสผ่านของคุณใหม่อีกครั้ง",
				"STR_LOGIN_PASSWORD_DIFFERENT":"คุณกรอกรหัสผ่านทั้งสองครั้งไม่เหมือนกัน กรุณากรอกใหม่อีกครั้ง",
				"STR_LOGIN_PASSWORD_CHARACTER":"รหัสผ่านไม่รวมสัญลักษณ์อื่น นอกจากอักษรภาษาอังกฤษและตัวเลข กรุณากรอกใหม่อีกครั้ง",
				"STR_LOGIN_REGISTER_SUCCESS":"ยินดีด้วย คุณลงทะเบียนบัญชีโป๊กเกอร์รอยัลสำเร็จ กดOKเข้าร่วมเกมส์เร็ว！",
				"STR_LOGIN_RETRIEVE_SUCCESS":"ส่งรหัสผ่านกู้คืนอีเมลเรียบร้อยแล้ว กรุณาเข้าอีเมลเพื่อตรวจรับ หากไม่ได้รับ กรุณารอสักครู่แล้วเช็คอีกครั้ง",
				"STR_LOGIN_RETRIEVE_FAIL":"บัญชีอีเมลที่คุณกรอกยังไม่ได้ลงทะเบียน กรุณาตรวจสอบและกรอกอีเมลที่ได้ลงทะเบียนแล้ว",
				"STR_MAIN_LOGOFF":"คุณแน่ใจหรือไม่ว่าจะล็อกเอาท์จากเกมส์？",
				"STR_MAIN_QUIT":"คุณแน่ใจหรือไม่ว่าจะออกจากเกมส์？",
				"STR_SHOP_CHIP":"ชิปของคุณไม่พอ ต้องการไปซื้อชิปที่ห้างหน่อยไหม？",
				"STR_SHOP_DIAMOND":"เพชรของคุณไม่พอ ต้องการไปซื้อเพชรที่ห้างหน่อยไหม？",
				"STR_SHOP_BUYSUCCESSFUL":"คุณได้ซื้อสินค้าสำเร็จแล้ว%s。",
				"STR_SHOP_REACHLIMIT":"คุณได้ซื้อไอเทมนี้ถึงขีดจำกัดแล้ว",
				"STR_SHOP_BUYFAIL":"ขออภัย ซื้อสินค้าล้มเหลว กรุณาลองใหม่อีกครั้ง",
				"STR_PLAYERSEARCH_SHORT":"เวลาค้นหาเพื่อน อย่างน้อยกรอก4ตัวอักษรภาษาอักกฤษหรือตัวเลข",
				"STR_PLAYERSEARCH_LONG":"เวลาค้นหาเพื่อน อย่างมากกรอกได้16ตัวอักษรภาษาอักกฤษหรือตัวเลข",
				"STR_FRIEND_HAVEADDED":"ผู้เล่นคนนี้อยู่ในรายการเพื่อนแล้ว",
				"STR_FRIEND_LIMIT":"จำนวนเพื่อนของคุณได้ถึงขีดจำกัดแล้ว คุณสามารถไปซื้อไอเทมสมุดรายชื่อได้ที่ห้าง เพื่ออัพระดับขีดจำกัดเพื่อน ",
				"STR_FRIEND_FOLLOW":"%s เพื่อนของคุณ กำลังเล่นไพ่อยู่ในห้อง%d/%d คุณยืนยันว่าจะตามเขาไปที่ห้องนั้นไหม？",
				"STR_FRIEND_DEL":"คุณแน่ใจว่าจะลบเพื่อนคนนี้หรือไม่？",
				"STR_FRIEND_ADDYOURSELF":"คุณไม่สามารถเพื่มตัวเองเป็นเพื่อนได้",
				"STR_PRESENT_NOTFRIEND":"เป็นเพื่อนถึงจะส่งชิปฟรีได้ คุณกับผู้เล่นคนนี้ยังไม่ได้เป็นเพื่อนกัน ส่งชิปให้ไม่ได้",
				"STR_PRESENT_DONE":"วันนี้คุณได้ส่งชิปให้เพื่อนคนนี้แล้ว พรุ่งนี้ค่อยส่งให้ใหม่นะ",
				"STR_PERSONAL_NAME_SHORT":"คุณกรอกชื่อสั้นเกินไป กรุณากรอกอย่างน้อย4ตัวอักษรภาษาอังกฤษหรือตัวเลข",
				"STR_PERSONAL_NAME_LONG":"คุณกรอกชื่อยาวเกินไป กรอกมากสุด16ตัวอักษรภาษาอังกฤษหรือตัวเลข",
				"STR_PERSONAL_NAME_REPEAK":"คุณกรอกชื่อซ้ำกับผู้อื่น กรุณากรอกชื่อใหม่อีกครั้ง",
				"STR_PERSONAL_NAME_ILLEGAL":"คุณกรอกชื่อผิดกฏ กรุณาใช้อักษรภาษาอังกฤษหรือตัวเลขกรอก",
				"STR_PERSONAL_SIGNATURE_LONG":"คุณกรอกสเตตัสยาวเกินไป กรอกได้มากสุด 120ตัวอักษร",
				"STR_PERSONAL_RECORDING_SHORT":"คุณอัดเสียงสั้นเกินไป กรุณาพูดยาวหน่อย",
				"STR_PERSONAL_QUICKVOICE_PLAY":"ตอนที่กำลังเล่นเสียง ไม่สามารถเปิดเสียงอื่นๆ ได้",
				"STR_PERSONAL_QUICKVOICE_RECORD":"ตอนที่กำลังเล่นเสียง ไม่สามารถอัดเสียงอื่นๆ ได้",
				"STR_PERSONAL_QUICKVOICE_DEL":"คุณแน่ใจหรือไม่ว่าจะลบเสียงสำเร็จรูปนี้？",
				"STR_PERSONAL_PHOTO_DEL":"คุณแน่ใจหรือไม่ว่าจะลบรูปภาพนี้？",
				"STR_PERSONAL_PHOTO_LIMIT":"จำนวนรูปภาพของคุณได้ถึงขีดจำกัดแล้ว คุณสามารถไปซื้อไอเทมอัลบัมรูปได้ที่ห้าง เพื่ออัพระดับขีดจำกัดรูปภาพ",
				"STR_PERSONAL_ACCOUNT_BINDING":"อีเมลที่คุณกรอกเคยถูกลงทะเบียนแล้ว กรุณากรอกอีเมลที่สามารถใช้งานได้ใหม่อีกครั้ง",
				"STR_PERSONAL_ITEMEXCHANGE_301002":"ยินดีด้วย คุณแลกเพชร%dเม็ดสำเร็จ ชิ้นส่วนที่สอดคล้องจะหักโดยอัตโนมัต",
				"STR_PERSONAL_ITEMEXCHANGE_302003":"ยินดีด้วย คุณแลกแว่นขยาย%dชิ้นสำเร็จ ชิ้นส่วนที่สอดคล้องจะหักโดยอัตโนมัต",
				"STR_PERSONAL_ITEMEXCHANGE_302001":"ยินดีด้วย คุณแลกไอเทมไมโครโฟน%dชิ้นสำเร็จ ชิ้นส่วนที่สอดคล้องจะหักโดยอัตโนมัต",
				"STR_PERSONAL_ITEMEXCHANGE_302002":"ยินดีด้วย คุณแลกไอเทมอิโมจิ%dชิ้นสำเร็จ ชิ้นส่วนที่สอดคล้องจะหักโดยอัตโนมัต",
				"STR_PERSONAL_BINDIN":"กรุณาใช้อีเมลที่ใช้งานอยู่เป็นประจำในการผูกบัญชี หลังจากผูกบัญชีแล้วจะสามารถใช้บัญชีล็อกอินเกมส์กับอุปกรณ์เครื่องอื่นได้",
				"STR_ITEM_TUREEYE_NULL":"จำนวนแว่นขยายของคุณไม่พอ ต้องการไปซื้อที่ห้างหน่อยไหม？",
				"STR_REPORT_PHOTO_CONFRIM":"คุณแน่ใจหรือไม่ว่าจะรายงานรูปภาพนี้？หลังจากรูปนี้ถูกผู้เล่นจำนวนมากรายงาน รูปภาพนี้จะถูกบล็อก เราจะเร่งดำเนินการตรวจสอบ",
				"STR_REPORT_PHOTO_REPEAK":"คุณได้รายงานรูปภาพนี้แล้ว กรุณาอย่ารายงานซ้ำ",
				"STR_SITDOWN_LIMIT":"จำนวนคนในห้องนี้เต็ม ไม่สามารถเข้าได้ กรุณาเลือกห้องอื่นที่มีที่ว่าง",
				"STR_SITDOWN_FULL":"ห้องนี้ไม่มีที่ว่าง กด“YES” ระบบจะจัดให้คุณไปอยู่ที่ห้องใหม่โดยอัตโนมัต กด“NO”คุณจะอยู่ที่เดิมเป็นผู้ชม",
				"STR_SITDOWN_REPEAK":"",
				"STR_SITDOWN_NOTEMPTY":"ที่นั่งที่คุณเลือกถูกผู้เล่นท่านอื่นนั่งแล้ว กรุณาเลือกที่นั่งว่างอื่น",
				"STR_TABLE_RECORDIND_SHORT":"คุณอัดเสียงสั้นเกินไป กรุณาอัดเสียงใหม่อีกครั้ง",
				"STR_ITEM_VOICE_NULL":"ไมโครโฟนของคุณไม่พอแล้ว ต้องการไปซื้อไมโครโฟนที่ห้างหน่อยไหม？",
				"STR_ITEM_VOICE_STAND":"ตอนนี้คุณยังไม่ได้นั่งลง ยังไม่สามารถใช้ฟังก์ชั่นสนทนาด้วยเสียงได้",
				"STR_ITEM_CHAT_STAND":"ตอนนี้คุณยังไม่ได้นั่งลง ยังไม่สามารถใช้การแชทและอิโมจิได้",
				"STR_ITEM_EXPRESSION_NULL":"อิโมจิของคุณไม่พอแล้ว ต้องการไปซื้ออิโมจิที่ห้างหน่อยไหม？",
				"STR_TABLE_LEAVE_SEAT":"ออกจากที่นั่งคุณจะเสียชิปที่ลงเดิมพันไปแล้ว คุณแน่ใจหรือไม่ว่าจะออกจากที่นั่งตอนนี้？",
				"STR_TABLE_LEAVE_ROOM":"ออกจากห้องคุณจะเสียชิปที่ลงเดิมพันไปแล้ว คุณแน่ใจหรือไม่ว่าจะออกจากห้องตอนนี้？",
				"STR_INVITE_RECEIVE":"ผู้เล่น%s เชิญคุณเข้าร่วมเล่นไพ่ กดยืนยัน",
				"STR_INVITE_CONFRIM":"ผู้เล่น%s เชิญคุณเข้าร่วมเล่นไพ่ ห้องID %d บิ๊กสมอลบลายด์%s / %s คุณแน่ใจหรือไม่ว่าต้องการเข้าร่วมเล่นไพ่？",
				"STR_INVITE_CONFRIM1":"ผู้เล่น%s เชิญคุณเข้าร่วมห้องเกมส์ของเขา\nห้องID%d เดิมพัน%s / %s\nคุณยืนยันจะเข้าร่วมห้องเกมส์ไหม？",
				"STR_INVITE_SAMEROOM":"คุณและผู้เล่นคนนี้อยู่ในห้องเดียวกันแล้ว",
				"STR_MISSION_COMPLETE":"คุณเสร็จสิ้น1ภารกิจแล้ว รีบไปกดรับรางวัลเร็ว",
				"STR_MUTE_ON":"คุณเปิดฟังก์ชั่นเงียบสำเร็จ",
				"STR_MUTE_OFF":"คุณปิดฟังก์ชั่นเงียบสำเร็จ",
				"STR_EQUIPMENT_MICROPHONE":"เปิดฟังก์ชั่นไมโครโฟนล้มเหลว กรุณายินยอมให้เกมส์เข้าใช้งานฟังก์ชั่นไมโครโฟนบนมือถือ กรุณาตรวจสอบการตั้งค่ามือถือ",
				"STR_ACHIEVEMENT_SUCCESS":"ยินดีด้วย！คุณกดรับรางวัลผลงานสำเร็จแล้ว%d %s.",
				"STR_LOGIN_OTHERDEVICES":"บัญชีของคุณถูกใช้งานที่อื่นแล้ว กรุณาตรวจสอบความปลอดภัยของรหัสผ่านบัญชีของคุณ เพื่อป้องกันความเสียหาย หากคุณมีข้อสงสัย กรุณาส่งอีเมลมาที่ฝ่ายบริการเรา",
				"STR_NETWORK_REQUEST":"เกิดข้อผิดพลาด%d คำร้องขออินเตอร์เน็ตล้มเหลว กรุณาตรวจสอบสภาพอินเตอร์เน็ตและลองใหม่อีกครั้ง",
				"STR_NETWORK_ERROR_CHECK":"อินเตอร์เน็ตเกิดข้อผิดพลาด การเชื่อมต่อถูกตัดขาด กรุณาตรวจสอบอุปกรณ์หรือการตั้งค่าอินเตอร์เน็ต",
				"STR_UNKNOWN_ERROR":"เกิดข้อผิดพลาดที่ระบุไม่ได้ เกมส์ไม่สามารถเข้าเล่นได้ปกติ คุณสามารถส่งอีเมลแจ้งฝ่ายบริการบอกรายละเอียดของข้อผิดพลาด",
				"STR_ERROR_DATA":"ข้อมูลเกมส์error กรุณาล็อกอินเกมส์ใหม่อีกครั้ง",
				"STR_EVALUATION_TEXT":"ผู้เล่นที่น่ารัก ตอนนี้คุณสามารถทำการให้คะแนนเกมส์เราได้แล้ว หลังจากให้คะแนนแล้วจะได้รับรางวัล ขอทราบว่าต้องการไปยังหน้าที่สอดคล้องหรือไม่？",
				"STR_GOOGLEPLAY_ERROR_1":"ในการซื้อนี้ต้องมีบริการGoogle Play หนึ่งรายการหรือมากกว่า ซึ่งตอนนี้ยังไม่สามารถใช้งานได้",
				"STR_GOOGLEPLAY_ERROR_2":"หลังอัพเดทบริการGoogle Playแล้ว ถึงจะสามารถทำการซื้อได้",
				"STR_GOOGLEPLAY_ERROR_3":"โทรศัพท์ของคุณไม่มีบริการGoogle Play คุณจำเป็นต้องติดตั้งบริการนี้ก่อน ถึงจะสามารถทำการซื้อได้",
				"STR_GOOGLEPLAY_ERROR_4":"คุณจำเป็นต้องเปิดบริการGoogle Playก่อน ถึงจะทำการซื้อได้",
				"STR_ITEM_NAME_301001":"ชิป",
				"STR_ITEM_NAME_301002":"เพชร",
				"STR_ITEM_NAME_302001":"ไมโครโฟน",
				"STR_ITEM_NAME_302002":"อิโมจิ",
				"STR_ITEM_NAME_302003":"แว่นขยาย",
				"STR_ITEM_NAME_303001":"ชิปทองคำ",
				"STR_ITEM_NAME_304001":"สมุดรายชื่อ",
				"STR_ITEM_NAME_304002":"อัลบัมรูป",
				"STR_ITEM_DESC_301001":"",
				"STR_ITEM_DESC_301002":"",
				"STR_ITEM_DESC_302001":"ใช้ฟังก์ชั่นสนทนาต้องเสียไอเทม ทุกครั้งที่ใช้สนทนา1ครั้ง ต้องเสีย1ไอเทม",
				"STR_ITEM_DESC_302002":"ใช้อิโมจิต้องเสียไอเทม ทุกครั้งที่ใช้อิโมจิ1ครั้ง ต้องเสีย1ไอเทม",
				"STR_ITEM_DESC_302003":"หลังจากใช้แล้ว สามารถตรวจเช็คข้อมูลเกมส์ของผู้เล่นได้ ทุกครั้งที่ตรวจเช็คผู้เล่น1ชื่อ ต้องเสีย1ไอเทม มีผลต่อเนื่อง%dนาที",
				"STR_ITEM_DESC_303001":"เพิ่มไอเทมของภารกิจรางวัลชิป ทุกภารกิจรางวัลชิปเปลี่ยนเป็น %sเท่า ต่อเนื่อง %dวัน",
				"STR_ITEM_DESC_304001":"",
				"STR_ITEM_DESC_304002":"",
				"STR_GOODS_NAME_401001":"%d แพ็คเพชร",
				"STR_GOODS_NAME_401002":"%d แพ็คเพชร",
				"STR_GOODS_NAME_401003":"%d แพ็คเพชร",
				"STR_GOODS_NAME_401004":"%d แพ็คเพชร",
				"STR_GOODS_NAME_402001":"%d แพ็คชิป",
				"STR_GOODS_NAME_402002":"%d แพ็คชิป",
				"STR_GOODS_NAME_402003":"%d แพ็คชิป",
				"STR_GOODS_NAME_402004":"%d แพ็คชิป",
				"STR_GOODS_NAME_403001":"%d แพ็คไมโครโฟน",
				"STR_GOODS_NAME_403002":"%d แพ็คไมโครโฟน",
				"STR_GOODS_NAME_404001":"%d แพ็คอิโมจิ",
				"STR_GOODS_NAME_404002":"%d แพ็คอิโมจิ",
				"STR_GOODS_NAME_405001":"%d แพ็คแว่นขยาย",
				"STR_GOODS_NAME_406001":"ชิปทองคำ",
				"STR_GOODS_NAME_407001":"สมุดรายชื่อ",
				"STR_GOODS_NAME_408001":"อัลบัมรูป",
				"STR_GOODS_DESC_401001":"เพชร %dเม็ด",
				"STR_GOODS_DESC_401002":"เพชร %dเม็ด",
				"STR_GOODS_DESC_401003":"เพชร %dเม็ด",
				"STR_GOODS_DESC_401004":"เพชร %dเม็ด",
				"STR_GOODS_DESC_402001":"%d ชิป",
				"STR_GOODS_DESC_402002":"%d ชิป",
				"STR_GOODS_DESC_402003":"%d ชิป",
				"STR_GOODS_DESC_402004":"%d ชิป",
				"STR_GOODS_DESC_403001":"ไมโครโฟน%dชิ้น ใช้ฟังก์ชั่นสนทนาต้องเสียไอเทม ทุกครั้งที่ใช้สนทนา1ครั้ง ต้องเสีย1ไอเทม",
				"STR_GOODS_DESC_403002":"ไมโครโฟน%dชิ้น ใช้ฟังก์ชั่นสนทนาต้องเสียไอเทม ทุกครั้งที่ใช้สนทนา1ครั้ง ต้องเสีย 1ไอเทม",
				"STR_GOODS_DESC_404001":"อิโมจิ%dชิ้น ใช้อิโมจิต้องเสียไอเทม ทุกครั้งที่ใช้อิโมจิ1ครั้ง ต้องเสียไอเทมอิโมจิ1ชิ้น",
				"STR_GOODS_DESC_404002":"อิโมจิ%dชิ้น ใช้อิโมจิต้องเสียไอเทม ทุกครั้งที่ใช้อิโมจิ1ครั้ง ต้องเสียไอเทมอิโมจิ1ชิ้น",
				"STR_GOODS_DESC_405001":"แว่นขยาย%dชิ้น หลังจากใช้แล้ว สามารถตรวจเช็คข้อมูลเกมส์ของผู้เล่นได้ ทุกครั้งที่ตรวจเช็คผู้เล่น1ชื่อ ต้องเสีย1ไอเทม มีผลต่อเนื่อง%dนาที",
				"STR_GOODS_DESC_406001":"เพิ่มไอเทมของภารกิจรางวัลชิป ทุกภารกิจรางวัลชิปเปลี่ยนเป็น %sเท่า ต่อเนื่อง %dวัน ซื้อหลายครั้ง เวลาต่อเนื่องยาวขึ้น",
				"STR_GOODS_DESC_407001":"ไอเทมอัพเกรดจำนวนเพื่อน เริ่มต้นจำกัดที่เพื่อน%dคน ทุกการมีสมุดรายชื่อ1ชิ้น ขีดจำกัดอัพเป็น%dคน ซื้อได้มากสุด%dชิ้น ราคาเปลี่ยนตามจำนวนที่ซื้อ",
				"STR_GOODS_DESC_408001":"ไอเทมอัพเกรดจำนวนรูปภาพ เริ่มต้นจำกัดรูปภาพ%dรูป ทุกการมีอัลบัมรูป1ชิ้น ขีดจำกัดอัพเป็น%dรูป ซื้อได้มากสุด%dชิ้น ราคาเปลี่ยนตามจำนวนที่ซื้อ",
				"STR_QUEST_DESC_101101":"เล่นไพ่ครบ 3รอบ",
				"STR_QUEST_DESC_101201":"เล่นเกมส์ 5นาที",
				"STR_QUEST_DESC_102101":"ชนะ 2รอบ",
				"STR_QUEST_DESC_102201":"ในช่วงPreflopชนะ 3ครั้ง",
				"STR_QUEST_DESC_102301":"หงายไพ่ชนะ 2ครั้ง",
				"STR_QUEST_DESC_103101":"ชิปชนะ(ยังไงเก็บค่าต๋ง)\nคือชิปที่ลงในรอบนี้เพิ่ม\n5เท่าขึ้นไป 1ครั้ง",
				"STR_QUEST_DESC_104101":"รอบที่มีชิปกองกลาง\nมากกว่า4 ชนะชิป\nทั้งหมด 1ครั้ง",
				"STR_QUEST_DESC_105101":"หลังจาก ALL In\nชนะไพ่ 3ครั้ง",
				"STR_QUEST_DESC_106101":"5คนหรือมากกว่าALL IN\nและชนะในที่สุด 1ครั้ง",
				"STR_QUEST_DESC_107101":"ตอนหงายไพ่ ใช้ไพ่\nรอยัลสเตรทฟลัช\nชนะ 1รอบ",
				"STR_QUEST_DESC_108101":"ตอนหงายไพ่ ใช้ไพ่สูง\nชนะ 1ครั้ง",
				"STR_QUEST_DESC_108201":"ตอนหงายไพ่ ใช้ไพ่1คู่\nชนะ 1ครั้ง",
				"STR_QUEST_DESC_108301":"ตอนหงายไพ่ ใช้ไพ่2คู่\nชนะ 1ครั้ง",
				"STR_QUEST_DESC_108401":"ตอนหงายไพ่ ใช้\nไพ่ตองชนะ 1ครั้ง",
				"STR_QUEST_DESC_108501":"ตอนหงายไพ่ ใช้\nไพ่สเตรทชนะ 1ครั้ง",
				"STR_QUEST_DESC_108601":"ตอนหงายไพ่ ใช้\nไพ่ฟลัชชนะ 1ครั้ง",
				"STR_QUEST_DESC_108701":"ตอนหงายไพ่ ใช้ไพ่\nฟูลเฮ้าท์ชนะ 1ครั้ง",
				"STR_QUEST_DESC_109101":"พูดคุย (รวมทั้งอิโมจิ\nแชท สนทนา) 20ครั้ง",
				"STR_QUEST_DESC_110101":"คอมเม้นต์รูปภาพ\nผู้เล่น 5ครั้ง",
				"STR_QUEST_DESC_101102":"เล่นไพ่ครบ 10รอบ",
				"STR_QUEST_DESC_101202":"เวลาเล่นเกมส์ผ่าน 15นาที",
				"STR_QUEST_DESC_102102":"ชนะ 5รอบ",
				"STR_QUEST_DESC_102202":"ในช่วงPreflopชนะ 9ครั้ง",
				"STR_QUEST_DESC_102302":"หงายไพ่ชนะ 5ครั้ง",
				"STR_QUEST_DESC_103102":"ชิปชนะ(ยังไงเก็บค่าต๋ง)\nคือชิปที่ลงในรอบนี้เพิ่ม\n5เท่าขึ้นไป 3ครั้ง",
				"STR_QUEST_DESC_104102":"รอบที่มีชิปกองกลาง\nมากกว่า4 ชนะชิป\nทั้งหมด 2ครั้ง",
				"STR_QUEST_DESC_105102":"หลังจาก ALL In\nชนะไพ่ 9ครั้ง",
				"STR_QUEST_DESC_106102":"5คนหรือมากกว่าALL IN\nและชนะในที่สุด 2ครั้ง",
				"STR_QUEST_DESC_107102":"ตอนหงายไพ่ ใช้รูปแบบ\nไพ่เหมือนกันชนะ\nผู้เล่นคนอื่น 2ครั้ง",
				"STR_QUEST_DESC_108102":"ตอนหงายไพ่ ใช้ไพ่สูง\nชนะ 2ครั้ง",
				"STR_QUEST_DESC_108202":"ตอนหงายไพ่ ใช้ไพ่1คู่\nชนะ 2ครั้ง",
				"STR_QUEST_DESC_108302":"ตอนหงายไพ่ ใช้ไพ่2คู่\nชนะ 2ครั้ง",
				"STR_QUEST_DESC_108402":"ตอนหงายไพ่ ใช้\nไพ่ตองชนะ 2ครั้ง",
				"STR_QUEST_DESC_108502":"ตอนหงายไพ่ ใช้\nไพ่สเตรทชนะ 2ครั้ง",
				"STR_QUEST_DESC_108602":"ตอนหงายไพ่ ใช้\nไพ่ฟลัชชนะ 2ครั้ง",
				"STR_QUEST_DESC_108702":"ตอนหงายไพ่ ใช้\nไพ่ฟูลเฮ้าท์ชนะ 2ครั้ง",
				"STR_QUEST_DESC_109102":"พูดคุย (รวมทั้งอิโมจิ\nแชท สนทนา) 50ครั้ง",
				"STR_QUEST_DESC_110102":"คอมเม้นต์รูปภาพ\nผู้เล่น 25ครั้ง",
				"STR_QUEST_DESC_101103":"เล่นไพ่ครบ 30รอบ",
				"STR_QUEST_DESC_101203":"เวลาเล่นเกมส์ผ่าน 30นาที",
				"STR_QUEST_DESC_102103":"ชนะ 10รอบ",
				"STR_QUEST_DESC_102203":"หลังแจกไพ่ชนะ 15ครั้ง",
				"STR_QUEST_DESC_102303":"หงายไพ่ชนะ 10ครั้ง",
				"STR_QUEST_DESC_103103":"ชิปชนะ(ยังไงเก็บค่าต๋ง)\nคือชิปที่ลงในรอบนี้เพิ่ม\n5เท่าขึ้นไป 1ครั้ง",
				"STR_QUEST_DESC_104103":"รอบที่มีชิปกองกลาง\nมากกว่า4 ชนะชิป\nทั้งหมด 3ครั้ง",
				"STR_QUEST_DESC_105103":"หลังจาก ALL In\nชนะไพ่ 15ครั้ง",
				"STR_QUEST_DESC_106103":"5คนหรือมากกว่าALL IN\nและชนะในที่สุด 3ครั้ง",
				"STR_QUEST_DESC_107103":"ตอนหงายไพ่ ใช้รูปแบบ\nไพ่เหมือนกันชนะผู้เล่น\nคนอื่น 3ครั้ง",
				"STR_QUEST_DESC_108103":"ตอนหงายไพ่ ใช้ไพ่สูง\nชนะ 3ครั้ง",
				"STR_QUEST_DESC_108203":"ตอนหงายไพ่ ใช้ไพ่1คู่\nชนะ 3ครั้ง",
				"STR_QUEST_DESC_108303":"ตอนหงายไพ่ ใช้ไพ่2คู่\nชนะ 3ครั้ง",
				"STR_QUEST_DESC_108403":"ตอนหงายไพ่ ใช้\nไพ่ตองชนะ 3ครั้ง",
				"STR_QUEST_DESC_108503":"ตอนหงายไพ่ ใช้ไพ่\nสเตรทชนะ 3ครั้ง",
				"STR_QUEST_DESC_108603":"ตอนหงายไพ่ ใช้ไพ่\nฟลัชชนะ 3ครั้ง",
				"STR_QUEST_DESC_108703":"ตอนหงายไพ่ ใช้ไพ่\nฟูลเฮ้าท์ชนะ 3ครั้ง",
				"STR_QUEST_DESC_109103":"พูดคุย (รวมทั้งอิโมจิ\nแชท สนทนา) 100ครั้ง",
				"STR_QUEST_DESC_110103":"คอมเม้นต์รูปภาพ\nผู้เล่น 50ครั้ง",
				"STR_ACHIVEVMENT_DESC_201001":"อัพเลเวลถึง 5",
				"STR_ACHIVEVMENT_DESC_201002":"อัพเลเวลถึง 10",
				"STR_ACHIVEVMENT_DESC_201003":"อัพเลเวลถึง 20",
				"STR_ACHIVEVMENT_DESC_201004":"อัพเลเวลถึง 35",
				"STR_ACHIVEVMENT_DESC_201005":"อัพเลเวลถึง 50",
				"STR_ACHIVEVMENT_DESC_202001":"ทรัพย์สินรวม 1ล้าน",
				"STR_ACHIVEVMENT_DESC_202002":"ทรัพย์สินรวม 10ล้าน",
				"STR_ACHIVEVMENT_DESC_202003":"ทรัพย์สินรวม 100ล้าน",
				"STR_ACHIVEVMENT_DESC_202004":"ทรัพย์สินรวม 1000ล้าน",
				"STR_ACHIVEVMENT_DESC_202005":"ทรัพย์สินรวม\n10000ล้าน",
				"STR_ACHIVEVMENT_DESC_203001":"เล่นไพ่ครบ 50รอบ",
				"STR_ACHIVEVMENT_DESC_203002":"เล่นไพ่ครบ 500รอบ",
				"STR_ACHIVEVMENT_DESC_203003":"เล่นไพ่ครบ 2500รอบ",
				"STR_ACHIVEVMENT_DESC_203004":"เล่นไพ่ครบ 10000รอบ",
				"STR_ACHIVEVMENT_DESC_203005":"เล่นไพ่ครบ 25000รอบ",
				"STR_ACHIVEVMENT_DESC_203006":"เล่นไพ่ครบ 50000รอบ",
				"STR_ACHIVEVMENT_DESC_203007":"เล่นไพ่ครบ 100000รอบ",
				"STR_ACHIVEVMENT_DESC_204001":"ชนะ 10รอบ",
				"STR_ACHIVEVMENT_DESC_204002":"ชนะ 100รอบ",
				"STR_ACHIVEVMENT_DESC_204003":"ชนะ 500รอบ",
				"STR_ACHIVEVMENT_DESC_204004":"ชนะ 2000รอบ",
				"STR_ACHIVEVMENT_DESC_204005":"ชนะ 5000รอบ",
				"STR_ACHIVEVMENT_DESC_204006":"ชนะ 10000รอบ",
				"STR_ACHIVEVMENT_DESC_204007":"ชนะ 20000รอบ",
				"STR_ACHIVEVMENT_DESC_205001":"ในช่วงPreflop\nชนะ 5รอบ",
				"STR_ACHIVEVMENT_DESC_205002":"ในช่วงPreflop\nชนะ 50รอบ",
				"STR_ACHIVEVMENT_DESC_205003":"ในช่วงPreflop\nชนะ 500รอบ",
				"STR_ACHIVEVMENT_DESC_205004":"ในช่วงPreflop\nชนะ 2500รอบ",
				"STR_ACHIVEVMENT_DESC_205005":"ในช่วงPreflop\nชนะ 10000รอบ",
				"STR_ACHIVEVMENT_DESC_206001":"หลังจาก ALL In\nชนะไพ่ 5รอบ",
				"STR_ACHIVEVMENT_DESC_206002":"หลังจาก ALL In\nชนะไพ่ 50รอบ",
				"STR_ACHIVEVMENT_DESC_206003":"หลังจาก ALL In\nชนะไพ่ 500รอบ",
				"STR_ACHIVEVMENT_DESC_206004":"หลังจาก ALL In\nชนะไพ่ 2500รอบ",
				"STR_ACHIVEVMENT_DESC_206005":"หลังจาก ALL In\nชนะไพ่ 10000รอบ",
				"STR_ACHIVEVMENT_DESC_207001":"ตอนหงายไพ่ ใช้ไพ่สูง\nชนะ 5รอบ",
				"STR_ACHIVEVMENT_DESC_207002":"ตอนหงายไพ่ ใช้ไพ่สูง\nชนะ 50รอบ",
				"STR_ACHIVEVMENT_DESC_207003":"ตอนหงายไพ่ ใช้ไพ่สูง\nชนะ 250รอบ",
				"STR_ACHIVEVMENT_DESC_207004":"ตอนหงายไพ่ ใช้ไพ่สูง\nชนะ 1000รอบ",
				"STR_ACHIVEVMENT_DESC_207005":"ตอนหงายไพ่ ใช้ไพ่สูง\nชนะ 3000รอบ",
				"STR_ACHIVEVMENT_DESC_208001":"ตอนหงายไพ่ ใช้ไพ่1คู่\nชนะ 5รอบ",
				"STR_ACHIVEVMENT_DESC_208002":"ตอนหงายไพ่ ใช้ไพ่1คู่\nชนะ 50รอบ",
				"STR_ACHIVEVMENT_DESC_208003":"ตอนหงายไพ่ ใช้ไพ่1คู่\nชนะ 500รอบ",
				"STR_ACHIVEVMENT_DESC_208004":"ตอนหงายไพ่ ใช้ไพ่1คู่\nชนะ 2000รอบ",
				"STR_ACHIVEVMENT_DESC_208005":"ตอนหงายไพ่ ใช้ไพ่1คู่\nชนะ 5000รอบ",
				"STR_ACHIVEVMENT_DESC_209001":"ตอนหงายไพ่ ใช้ไพ่2คู่\nชนะ 5รอบ",
				"STR_ACHIVEVMENT_DESC_209002":"ตอนหงายไพ่ ใช้ไพ่2คู่\nชนะ 50รอบ",
				"STR_ACHIVEVMENT_DESC_209003":"ตอนหงายไพ่ ใช้ไพ่2คู่\nชนะ 500รอบ",
				"STR_ACHIVEVMENT_DESC_209004":"ตอนหงายไพ่ ใช้ไพ่2คู่\nชนะ 2000รอบ",
				"STR_ACHIVEVMENT_DESC_209005":"ตอนหงายไพ่ ใช้ไพ่2คู่\nชนะ 5000รอบ",
				"STR_ACHIVEVMENT_DESC_210001":"ตอนหงายไพ่ ใช้\nไพ่ตองชนะ 5รอบ",
				"STR_ACHIVEVMENT_DESC_210002":"ตอนหงายไพ่ ใช้\nไพ่ตองชนะ 50รอบ",
				"STR_ACHIVEVMENT_DESC_210003":"ตอนหงายไพ่ ใช้\nไพ่ตองชนะ 500รอบ",
				"STR_ACHIVEVMENT_DESC_210004":"ตอนหงายไพ่ ใช้\nไพ่ตองชนะ 2000รอบ",
				"STR_ACHIVEVMENT_DESC_210005":"ตอนหงายไพ่ ใช้\nไพ่ตองชนะ 5000รอบ",
				"STR_ACHIVEVMENT_DESC_211001":"ตอนหงายไพ่ ใช้\nไพ่สเตรทชนะ 5รอบ",
				"STR_ACHIVEVMENT_DESC_211002":"ตอนหงายไพ่ ใช้\nไพ่สเตรทชนะ 50รอบ",
				"STR_ACHIVEVMENT_DESC_211003":"ตอนหงายไพ่ ใช้\nไพ่สเตรทชนะ 500รอบ",
				"STR_ACHIVEVMENT_DESC_211004":"ตอนหงายไพ่ ใช้\nไพ่สเตรทชนะ 2000รอบ",
				"STR_ACHIVEVMENT_DESC_211005":"ตอนหงายไพ่ ใช้\nไพ่สเตรทชนะ 5000รอบ",
				"STR_ACHIVEVMENT_DESC_212001":"ตอนหงายไพ่ ใช้\nไพ่ฟลัชชนะ 5รอบ",
				"STR_ACHIVEVMENT_DESC_212002":"ตอนหงายไพ่ ใช้\nไพ่ฟลัชชนะ 50รอบ",
				"STR_ACHIVEVMENT_DESC_212003":"ตอนหงายไพ่ ใช้\nไพ่ฟลัชชนะ 250รอบ",
				"STR_ACHIVEVMENT_DESC_212004":"ตอนหงายไพ่ ใช้\nไพ่ฟลัชชนะ 1000รอบ",
				"STR_ACHIVEVMENT_DESC_212005":"ตอนหงายไพ่ ใช้\nไพ่ฟลัชชนะ 3000รอบ",
				"STR_ACHIVEVMENT_DESC_213001":"ตอนหงายไพ่ ใช้\nไพ่ฟูลเฮ้าท์ชนะ 3รอบ",
				"STR_ACHIVEVMENT_DESC_213002":"ตอนหงายไพ่ ใช้\nไพ่ฟูลเฮ้าท์ชนะ 30รอบ",
				"STR_ACHIVEVMENT_DESC_213003":"ตอนหงายไพ่ ใช้\nไพ่ฟูลเฮ้าท์ชนะ 200รอบ",
				"STR_ACHIVEVMENT_DESC_213004":"ตอนหงายไพ่ ใช้\nไพ่ฟูลเฮ้าท์ชนะ 500รอบ",
				"STR_ACHIVEVMENT_DESC_213005":"ตอนหงายไพ่ ใช้\nไพ่ฟูลเฮ้าท์ชนะ 1000รอบ",
				"STR_ACHIVEVMENT_DESC_214001":"ตอนหงายไพ่ ใช้\nไพ่โฟร์การ์ดชนะ 2รอบ",
				"STR_ACHIVEVMENT_DESC_214002":"ตอนหงายไพ่ ใช้\nไพ่โฟร์การ์ดชนะ 10รอบ",
				"STR_ACHIVEVMENT_DESC_214003":"ตอนหงายไพ่ ใช้\nไพ่โฟร์การ์ดชนะ 50รอบ",
				"STR_ACHIVEVMENT_DESC_214004":"ตอนหงายไพ่ ใช้\nไพ่โฟร์การ์ดชนะ 200รอบ",
				"STR_ACHIVEVMENT_DESC_214005":"ตอนหงายไพ่ ใช้\nไพ่โฟร์การ์ดชนะ 500รอบ",
				"STR_ACHIVEVMENT_DESC_215001":"ตอนหงายไพ่ ได้รับ\nไพ่โฟร์การ์ดทุกเลข\nเริ่มA-K",
				"STR_ACHIVEVMENT_DESC_216001":"ตอนหงายไพ่ ใช้\nไพ่ฟลัชชนะ 1รอบ",
				"STR_ACHIVEVMENT_DESC_216002":"ตอนหงายไพ่ ใช้\nไพ่ฟลัชชนะ 5รอบ",
				"STR_ACHIVEVMENT_DESC_216003":"ตอนหงายไพ่ ใช้\nไพ่ฟลัชชนะ 20รอบ",
				"STR_ACHIVEVMENT_DESC_216004":"ตอนหงายไพ่ ใช้\nไพ่ฟลัชชนะ 50รอบ",
				"STR_ACHIVEVMENT_DESC_216005":"ตอนหงายไพ่ ใช้\nไพ่ฟลัชชนะ 100รอบ",
				"STR_ACHIVEVMENT_DESC_217001":"ตอนหงายไพ่ ใช้\nไพ่รอยัลสเตรทฟลัช\nชนะ 1รอบ",
				"STR_ACHIVEVMENT_DESC_217002":"ตอนหงายไพ่ ใช้\nไพ่รอยัลสเตรทฟลัช\nชนะ 2รอบ",
				"STR_ACHIVEVMENT_DESC_217003":"ตอนหงายไพ่ ใช้\nไพ่รอยัลสเตรทฟลัช\nชนะ 5รอบ",
				"STR_ACHIVEVMENT_DESC_217004":"ตอนหงายไพ่ ใช้\nไพ่รอยัลสเตรทฟลัช\nชนะ 10รอบ",
				"STR_ACHIVEVMENT_DESC_217005":"ตอนหงายไพ่ ใช้\nไพ่รอยัลสเตรทฟลัช\nชนะ 20รอบ",
				"STR_ACHIVEVMENT_DESC_218001":"ได้รับไพ่รอยัลสเตรทฟลัช\nทุกดอกและสี",
				"STR_ACHIVEVMENT_DESC_219001":"ใช้สนทนาเสียง 20ครั้ง",
				"STR_ACHIVEVMENT_DESC_219002":"ใช้สนทนาเสียง 100ครั้ง",
				"STR_ACHIVEVMENT_DESC_219003":"ใช้สนทนาเสียง 500ครั้ง",
				"STR_ACHIVEVMENT_DESC_219004":"ใช้สนทนาเสียง 2500ครั้ง",
				"STR_ACHIVEVMENT_DESC_219005":"ใช้สนทนาเสียง 10000ครั้ง",
				"STR_ACHIVEVMENT_DESC_220001":"ใช้อิโมจิ 50ครั้ง",
				"STR_ACHIVEVMENT_DESC_220002":"ใช้อิโมจิ 250ครั้ง",
				"STR_ACHIVEVMENT_DESC_220003":"ใช้อิโมจิ 1000ครั้ง",
				"STR_ACHIVEVMENT_DESC_220004":"ใช้อิโมจิ 5000ครั้ง",
				"STR_ACHIVEVMENT_DESC_220005":"ใช้อิโมจิ 20000ครั้ง",
				"STR_ACHIVEVMENT_DESC_221001":"จำนวนเพื่อนถึง 5คน",
				"STR_ACHIVEVMENT_DESC_221002":"จำนวนเพื่อนถึง 20คน",
				"STR_ACHIVEVMENT_DESC_221003":"จำนวนเพื่อนถึง 50คน",
				"STR_ACHIVEVMENT_DESC_222001":"อัพโหลดรูป 1รูป",
				"STR_ACHIVEVMENT_DESC_222002":"อัพโหลดรูป 10รูป",
				"STR_ACHIVEVMENT_DESC_222003":"อัพโหลดรูป 100รูป",
				"STR_ACHIVEVMENT_DESC_223001":"ได้รับกดไลค์ 5ครั้ง",
				"STR_ACHIVEVMENT_DESC_223002":"ได้รับกดไลค์ 50ครั้ง",
				"STR_ACHIVEVMENT_DESC_223003":"ได้รับกดไลค์ 500ครั้ง",
				"STR_ACHIVEVMENT_DESC_224001":"ให้ไลค์ 5ครั้ง",
				"STR_ACHIVEVMENT_DESC_224002":"ให้ไลค์ 50ครั้ง",
				"STR_ACHIVEVMENT_DESC_224003":"ให้ไลค์ 500ครั้ง",
				"STR_ACHIVEVMENT_DESC_225001":"รูปของตัวเองได้รับ\nคอมเม้นต์ 10ครั้ง",
				"STR_ACHIVEVMENT_DESC_225002":"รูปของตัวเองได้รับ\nคอมเม้นต์ 100ครั้ง",
				"STR_ACHIVEVMENT_DESC_225003":"รูปของตัวเองได้รับ\nคอมเม้นต์ 1000ครั้ง",
				"STR_ACHIVEVMENT_DESC_226001":"คอมเม้นต์รูป\nคนอื่น 10ครั้ง",
				"STR_ACHIVEVMENT_DESC_226002":"คอมเม้นต์รูป\nคนอื่น 100ครั้ง",
				"STR_ACHIVEVMENT_DESC_226003":"คอมเม้นต์รูป\nคนอื่น 1000ครั้ง",
				"STR_ACHIVEVMENT_DESC_227001":"เสร็จ 5ภารกิจ",
				"STR_ACHIVEVMENT_DESC_227002":"เสร็จ 50ภารกิจ",
				"STR_ACHIVEVMENT_DESC_227003":"เสร็จ 500ภารกิจ",
				"STR_ACHIVEVMENT_DESC_227004":"เสร็จ 2500ภารกิจ",
				"STR_ACHIVEVMENT_DESC_227005":"เสร็จ 10000ภารกิจ",
				"STR_ACHIVEVMENT_DESC_228001":"แลกไอเทม 5ครั้ง",
				"STR_ACHIVEVMENT_DESC_228002":"แลกไอเทม 50ครั้ง",
				"STR_ACHIVEVMENT_DESC_228003":"แลกไอเทม 500ครั้ง",
				"STR_ACHIVEVMENT_DESC_229001":"ให้ชิปผู้เล่นคนอื่น\nบนโต๊ะไพ่ 10ครั้ง",
				"STR_ACHIVEVMENT_DESC_229002":"ให้ชิปผู้เล่นคนอื่น\nบนโต๊ะไพ่ 100ครั้ง",
				"STR_ACHIVEVMENT_DESC_229003":"ให้ชิปผู้เล่นคนอื่น\nบนโต๊ะไพ่ 1000ครั้ง",
				"STR_ACHIVEVMENT_DESC_230001":"ส่งชิปฟรีให้เพื่อน 10ครั้ง",
				"STR_ACHIVEVMENT_DESC_230002":"ส่งชิปฟรีให้เพื่อน 100ครั้ง",
				"STR_ACHIVEVMENT_DESC_230003":"ส่งชิปฟรีให้เพื่อน 1000ครั้ง",
				"STR_ACHIVEVMENT_DESC_231001":"ได้รับชิปฟรีรวมถึง100000",
				"STR_ACHIVEVMENT_DESC_231002":"ได้รับชิปฟรีรวมถึง250000",
				"STR_ACHIVEVMENT_DESC_231003":"ได้รับชิปฟรีรวมถึง 1ล้าน",
				"STR_ACHIVEVMENT_DESC_232001":"จำนวนวันล็อกอิน\nสะสมติดถึง 5วัน",
				"STR_ACHIVEVMENT_DESC_232002":"จำนวนวันล็อกอิน\nสะสมติดถึง 25วัน",
				"STR_ACHIVEVMENT_DESC_232003":"จำนวนวันล็อกอิน\nสะสมติดถึง 100วัน",
				"STR_ACHIVEVMENT_DESC_232004":"จำนวนวันล็อกอิน\nสะสมติดถึง 250วัน",
				"STR_ACHIVEVMENT_DESC_232005":"จำนวนวันล็อกอิน\nสะสมติดถึง 500วัน",
				"STR_LOGIN_VERSION":"เวอร์ชั่น：",
				"STR_INFORMATION_PERSONAL_SIGNATURE_DEFAULT":"ผู้เล่นคนนี้ยังไม่ได้เขียนข้อความใดๆ เลย อยากให้คนติดตามเยอะๆ ไหม？\nเขียนสเตตัสสักหน่อยนะ",
				"STR_MESS_EVALUATION_TITLE":"ขอบคุณสำหรับการให้คะแนน",
				"STR_MESS_EVALUATION_CONTENT":"เพราะว่าคุณได้ให้การสนับสนุนและให้คะแนนเกมส์ของเราระบบได้ส่ง%d เป็นชิปรางวัลให้คุณ กรุณากดรับด่วน",
    
};
