 module.exports = {
				"STR_COREPLAY_BUTTON_FOLD":"弃牌",
				"STR_COREPLAY_BUTTON_CHECK":"看牌",
				"STR_COREPLAY_BUTTON_CALL":"跟注 %s",
				"STR_COREPLAY_BUTTON_RAISE":"加注",
				"STR_COREPLAY_BUTTON_CONFIRM":"确定",
				"STR_COREPLAY_BUTTON_ALLIN":"全下",
				"STR_COREPLAY_BUTTON_PREP_CHECKORFOLD":"看/弃",
				"STR_COREPLAY_BUTTON_PREP_AUTOCHECK":"看牌",
				"STR_COREPLAY_BUTTON_PREP_CALL":"跟注 %s",
				"STR_COREPLAY_BUTTON_PREP_CALLANY":"跟任何注",
				"STR_INFORMATION_TILLE_1":"个人信息",
				"STR_INFORMATION_TILLE_2":"道具清单",
				"STR_INFORMATION_TILLE_3":"快捷文字",
				"STR_INFORMATION_TILLE_4":"快捷语音",
				"STR_INFORMATION_TILLE_5":"数据统计",
				"STR_INFORMATION_PERSONAL_LV":"等级",
				"STR_INFORMATION_PERSONAL_ID":"ID",
				"STR_INFORMATION_PERSONAL_NAME":"昵称",
				"STR_INFORMATION_PERSONAL_MALE":"男性",
				"STR_INFORMATION_PERSONAL_FEMALE":"女性",
				"STR_INFORMATION_PERSONAL_ADDRESS":"地址",
				"STR_INFORMATION_PERSONAL_ADDRESS_NULL":"未知",
				"STR_INFORMATION_PERSONAL_SIGNATURE":"签名",
				"STR_INFORMATION_PERSONAL_PHOTO_DEFAULT":"上传一张新照片",
				"STR_INFORMATION_PERSONAL_PHOTO_INREVIEW":"审核中",
				"STR_INFORMATION_ITEMLIST_TIME":"天",
				"STR_INFORMATION_ITEMLIST_TIME_HOUR":"小时",
				"STR_INFORMATION_QUICKCHAT_WORDS":"快捷文字 %d",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_1":"游戏开始了，我已经准备好赢钱了",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_2":"不要耽误时间了，赶快下注吧",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_3":"手牌这么好，看来这局是我赢了。",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_4":"让我all-in，怕的人就赶快弃牌吧。",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_5":"虽然这局我赢了，但是我依然不会手下留情的",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_6":"弃牌也未必代表我输了,让我先休息一下。",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_7":"你牌打得真好，连我都忍不住要称赞你了",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_8":"居然有这种事，简直不能相信",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_9":"这一局我没认真玩，下次不会输了。",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_10":"我大发慈悲的离开了，你们就庆幸吧。",
				"STR_INFORMATION_QUICKCHAT_WORDS_DEFAULT_NULL":"点击此处输入您的快捷文字",
				"STR_INFORMATION_QUICKCHAT_VOICE":"快捷语音 %d",
				"STR_INFORMATION_QUICKCHAT_VOICE_DEFAULT":"长按此处进行录音",
				"STR_INFORMATION_QUICKCHAT_VOICE_ENTERTITLE":"点击此处输入标题",
				"STR_INFORMATION_QUICKCHAT_VOICE_RECORDING":"正在录入",
				"STR_INFORMATION_STATISTICS_ID":"ID:",
				"STR_INFORMATION_STATISTICS_GAMES":"游戏局数:",
				"STR_INFORMATION_STATISTICS_WINS":"获胜局数",
				"STR_INFORMATION_STATISTICS_LOSE":"失败局数",
				"STR_INFORMATION_STATISTICS_WINRATE":"胜率:",
				"STR_INFORMATION_STATISTICS_SHOWINRIVER":"亮牌率:",
				"STR_INFORMATION_STATISTICS_FOLDINPREFLOP":"首轮弃牌率:",
				"STR_INFORMATION_STATISTICS_ALLININPREFLOP":"首轮全下率:",
				"STR_INFORMATION_STATISTICS_HIGHESTCHIP":"历史最多筹码:",
				"STR_INFORMATION_STATISTICS_MOSTWIN":"最大赢取:",
				"STR_INFORMATION_STATISTICS_BESTCARDS":"最大牌型:",
				"STR_INFORMATION_STATISTICS_GIVECHIPTOFRIEND":"赠送好友免费筹码次数:",
				"STR_INFORMATION_STATISTICS_GIVECHIPTOFRIEND_TIMES":"次",
				"STR_INFORMATION_STATISTICS_GIVECHIPINGAME":"赠送玩家筹码次数:",
				"STR_INFORMATION_STATISTICS_GIVECHIPINGAME_TIMES":"次",
				"STR_INFORMATION_ITEMLIST_ITEM_TITLE":"您拥有的：",
				"STR_INFORMATION_ITEMLIST_PATCH_TITLE":"您可兑换：",
				"STR_RANKING_TITLE_MAIN":"排行版",
				"STR_RANKING_TITLE_1":"总筹码",
				"STR_RANKING_TITLE_2":"单词赢取倍率",
				"STR_RANKING_TITLE_3":"筹码波动",
				"STR_RANKING_TITLE_4":"今日赢取",
				"STR_RANKING_TITLE_5":"互动",
				"STR_RANKING_GMT_GMT":"格林威治时间",
				"STR_RANKING_GMT_EXPLAIN":"游戏服务器采用格林威治时间为标准。此处显示的是格林威治时间，请各位玩家注意。",
				"STR_RANKING_TOP_TOP":"前列",
				"STR_RANKING_RANKING_NOPLAYER":"排行榜上没有玩家",
				"STR_CHAT_EXPRESSION_TITLE":"表情",
				"STR_CHAT_QUICKWORDS_TITLE":"快捷文字",
				"STR_CHAT_QUICKVOICES_TITLE":"快捷语音",
				"STR_CHAT_INPUT_DEFAULT":"点击此处输入您的文字",
				"STR_CHAT_INPUT_DEFAULT_IOS":"点击此处输入您的文字",
				"STR_CHAT_QUICKVOICE_NOVICE":"没有快捷语音",
				"STR_CHAT_QUICKVOICE_NOTITLE":"没有输入描述",
				"STR_TABLEBOARD_CAHT_NOQUICKVOICE":"您目前还没有预先录入的快捷语音。",
				"STR_TABLEBOARD_CHAT_NOQUICKTEXT":"您目前还没有预先输入的快捷文字。",
				"STR_TABLEBOARD_RECORDING_COUNTDOWN":"剩余%d 秒",
				"STR_FRIENDS_TITLE":"您的好友",
				"STR_FRIENDS_NOFRIENDS":"您目前还没有好友。点击右上角的搜索按键，您可以通过玩家昵称找到相应的玩家。在牌桌界面和主界面上点击玩家头像，点击加好友按键也能轻松的发送好友申请，快去尝试下吧。",
				"STR_FRIENDS_FRIENDS_UPDATE":"优先显示更新了照片的好友",
				"STR_FRIENDS_FRIENDS_OL":"优先显示在线的好友",
				"STR_FRIENDS_FRIENDS_ACTIVE":"优先显示较活跃的好友",
				"STR_FRIENDS_FRIENDS_MAX":"MAX",
				"STR_FRIENDS_FRIENDS_INFORMATION_LV":"等级:",
				"STR_FRIENDS_FRIENDS_INFORMATION_MALE":"男性",
				"STR_FRIENDS_FRIENDS_INFORMATION_FEMALE":"女性",
				"STR_FRIENDS_FRIENDS_INFORMATION_ADDRESS":"地址",
				"STR_FRIENDS_FRIENDS_INFORMATION_DEFAULT":"显示您给予了该玩家多少赞，评论和免费筹码赠送次数",
				"STR_FRIENDS_FRIENDS_INFORMATION_NOPHOTO":"该玩家没有上传任何照片",
				"STR_FRIENDS_FRIENDS_INFORMATION_GAMES":"游戏",
				"STR_FRIENDS_FRIENDS_INFORMATION_WIN":"胜利",
				"STR_FRIENDS_FRIENDS_INFORMATION_LOSE":"失败",
				"STR_FRIENDS_FRIENDS_INFORMATION_WINRATE":"胜率:",
				"STR_FRIENDS_FRIENDS_INFORMATION_SHOWINRIVER":"亮牌率:",
				"STR_FRIENDS_FRIENDS_INFORMATION_FOLDINPREFLOP":"首轮弃牌率:",
				"STR_FRIENDS_FRIENDS_INFORMATION_ALLININPREFLOP":"首轮全下率:",
				"STR_FRIENDS_FRIENDS_INFORMATION_HIGHESTCHIP":"历史最多筹码:",
				"STR_FRIENDS_FRIENDS_INFORMATION_MOSTWIN":"最大赢取:",
				"STR_FRIENDS_FRIENDS_INFORMATION_BESTCARDS":"最大牌型:",
				"STR_FRIENDS_FRIENDS_SEARCHTITLE":"搜索到的好友",
				"STR_FRIENDS_FRIENDS_SEARCHTIPS":"请至少输入四个字符来搜索昵称",
				"STR_FRIENDS_FRIENDS_SEARCH":"根据玩家昵称找到了 %d 个玩家。最多能显示 %d 个相关玩家。",
				"STR_LOGIN_PHONELOGIN":"手机登录",
				"STR_LOGIN_ACCOUNTLOGIN":"账号登陆",
				"STR_LOGIN_FACEBOOKLOGIN":"Facebook登陆",
				"STR_LOGIN_GUESTLOGIN":"游客登陆",
				"STR_LOGIN_ACCOUNTLOGIN_ACCOUNT":"输入您的邮箱",
				"STR_LOGIN_ACCOUNTLOGIN_PASSWORD":"输入您的密码",
				"STR_LOGIN_ACCOUNTLOGIN_AUTOLOGIN":"自动登录",
				"STR_LOGIN_ACCOUNTLOGIN_RETRIEVEPASSWORD":"找回密码",
				"STR_LOGIN_ACCOUNTLOGIN_LOGIN":"登录",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTER":"注册",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTERACCOUNT":"请输入您的邮箱",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTERENTERPASSWORD":"请输入密码",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTERCONFRIMPASSWORD":"请确认密码",
				"STR_LOGIN_ACCOUNTLOGIN_REGISTERREGISTER":"注册",
				"STR_LOGIN_ACCOUNTLOGIN_RETRIEVEPASSWORD_EXPLAIN":"如果你想找回密码，请输入你注册账号时所使用的邮箱，我们会将密码找回邮件发送至该邮箱中。",
				"STR_LOGIN_ACCOUNTLOGIN_RETRIEVEPASSWORD_ENTER":"请输入你的注册邮箱",
				"STR_LOGIN_ACCOUNTLOGIN_RETRIEVEPASSWORD_SENDEMAIL":"发送邮件",
				"STR_LOGIN_TERMSOFSERVICE":"用户协议",
				"STR_LOBBY_TITLE":"房间",
				"STR_LOBBY_ID":"房间ID",
				"STR_LOBBY_BLIND":"盲注 %s/%s",
				"STR_LOBBY_5PLAYERS":"5人场",
				"STR_LOBBY_9PLAYERS":"9人场",
				"STR_LOBBY_FULL":"满房间",
				"STR_LOBBY_EMPTY":"空房间",
				"STR_SIT_ROOMID":"房间ID %d",
				"STR_SIT_BLIND":"大小盲注 %s/%s",
				"STR_SIT_MINBLIND":"最小带入",
				"STR_SIT_MAXBLIND":"最大带入",
				"STR_SIT_AUTOSIT":"筹码不足时自动带入筹码并坐下",
				"STR_SIT_LEAVE":"离开",
				"STR_SIT_SIT":"坐下",
				"STR_SIT_NOCHIP":"筹码不足",
				"STR_SIT_SHOP":"商店",
				"STR_INVITE_TITLE":"和您的朋友一起玩",
				"STR_INVITE_BUTTON":"邀请到牌桌",
				"STR_INVITE_NOFRIEND":"很遗憾，您还没有任何好友。快去和其他玩家交友吧。",
				"STR_INVITE_UNKNOWN":"地址未知",
				"STR_MES_FRIEND_TITLE":"好友消息",
				"STR_MES_SYSTEM_TITLE":"系统消息",
				"STR_MES_ADDFRIEND_RCCEIVE":"%s 想要和您成为好友。请问你要同意吗？",
				"STR_MES_ADDFRIEND_AGREE":"恭喜！%s 已经通过了您的好友申请，您可以在好友界面找到他。",
				"STR_MES_ADDFRIEND_YOUAGREE":"您通过了 %s 的好友申请，您可以在好友界面找到他。",
				"STR_MES_CHIPS_GIVE":"%s 赠送给您 %d 免费筹码，快来接受吧。",
				"STR_MES_CHIPS_RECEIVE":"您接受了来自 %s 的 %d 免费筹码。",
				"STR_MES_MESSAGE_NULL":"目前为止没有消息。",
				"STR_MES_MONTH_JAN":"一月",
				"STR_MES_MONTH_FEB":"二月",
				"STR_MES_MONTH_MAR":"三月",
				"STR_MES_MONTH_APR":"四月",
				"STR_MES_MONTH_MAY":"五月",
				"STR_MES_MONTH_JUN":"六月",
				"STR_MES_MONTH_JUL":"七月",
				"STR_MES_MONTH_AUG":"八月",
				"STR_MES_MONTH_SEP":"九月",
				"STR_MES_MONTH_OCT":"十月",
				"STR_MES_MONTH_NOV":"十一月",
				"STR_MES_MONTH_DEC":"十二月",
				"STR_HOMESCREEN_OLPLAYER":"%s 玩家在线",
				"STR_HOMESCREEN_PHOTOUPLOAD":"你的好友 %s 更新了照片",
				"STR_HOMESCREEN_NOUPLOAD":"没有好友更新照片",
				"STR_EVENT_BACK":"返回",
				"STR_ANNOUNCEMENT_TITLE":"公告",
				"STR_PLAYER_INF_NAME":"姓名",
				"STR_PLAYER_INF_TITLE_PHOTO":"照片",
				"STR_PLAYER_INF_TITLE_ACHIEVEMENTS":"成就",
				"STR_PLAYER_INF_LV":"等级",
				"STR_PLAYER_INF_MALE":"男性",
				"STR_PLAYER_INF_FEMALE":"女性",
				"STR_PLAYER_INF_ADDRESS":"地址",
				"STR_PLAYER_INF_BUTTON_BLOCK":"点击这里屏蔽玩家",
				"STR_PLAYER_INF_BLOCKBUTTON":"屏蔽",
				"STR_PLAYER_INF_BUTTON_UNLOCK":"点击这里解除屏蔽",
				"STR_PLAYER_INF_UNLOCKBUTTON":"解除屏蔽",
				"STR_PLAYER_INF_BUTTON_REPORT":"点击这里举报玩家头像",
				"STR_PLAYER_INF_REPORTBUTTON":"举报",
				"STR_PLAYER_INF_BLOCK":"屏蔽后，你将不会再收到任何来自该玩家的文字，语音或表情。您确定要屏蔽这名玩家吗？",
				"STR_PLAYER_INF_UNBLOCK":"解除对该玩家的屏蔽后，你可以再次收到来自该玩家的文字，语音或表情。",
				"STR_PLAYER_INF_REPORT":"有多名玩家举报此头像后，该头像将被屏蔽。我们将尽快进行审核。您确定要举报这个头像吗？",
				"STR_PLAYER_PHOTO_NULL":"该玩家并未上传任何照片。",
				"STR_CHECKPHOTO_NOAUTHORITY":"抱歉，由于该玩家的设置，您没有查看该玩家照片的权限。",
				"STR_PLAYER_PHOTO_CRITICTITLE":"评论",
				"STR_PLAYER_STATISTICS_GAMES":"游戏局数:",
				"STR_PLAYER_STATISTICS_WINS":"胜利",
				"STR_PLAYER_STATISTICS_LOSE":"失败",
				"STR_PLAYER_STATISTICS_WINRATE":"胜率:",
				"STR_PLAYER_STATISTICS_SHOWINRIVER":"亮牌率:",
				"STR_PLAYER_STATISTICS_FOLDINPREFLOP":"首轮弃牌率:",
				"STR_PLAYER_STATISTICS_ALLININPREFLOP":"首轮全下率:",
				"STR_PLAYER_STATISTICS_HIGHESTCHIPS":"历史最多筹码:",
				"STR_PLAYER_STATISTICS_MOSTWIN":"最大赢取:",
				"STR_PLAYER_STATISTICS_BTESTCARD":"最大牌型:",
				"STR_PLAYER_STATISTICS_MINS":"%s 分钟",
				"STR_PLAYER_ACHIEVEMENT_NULL":"该玩家还没有获得任何成就。",
				"STR_LOGINREWARD_TITLE":"连续登陆奖励",
				"STR_LOGINREWARD_DAY":"第 %d 天",
				"STR_LOGINREWARD_RECEIVED":"已经领取",
				"STR_LOGINREWARD_TIPS":"如果你您保持连续登陆，您将获得更丰厚的奖励。",
				"STR_LOGINREWARD_SUCCESS":"恭喜你领取了每日登录奖励 %d %s。",
				"STR_ABOUTUS_STAFF":"Poker Royal Texas Hold'em Staff List\n\n\nGameDesinger\n\nStone\nJohn Smith\n\n\nProgrammer\n\nJack\nWillian\nHaven \nSpiro\nBob\nRussell\n\n\nArtDesinger\n\nPantheon\nEmma\nMandy\n\n\nGameTester\n\nJoffence\nDoris\n\n\nSpecial Thanks\n\nChris\nAlex\nMatata\nBlank",
				"STR_BUTTON_YES":"是",
				"STR_BUTTON_NO":"否",
				"STR_BUTTON_OK":"确定",
				"STR_BUTTON_IGNORE":"忽略",
				"STR_BUTTON_AGREE":"同意",
				"STR_OPTIONS_TITLE":"设置",
				"STR_OPTIONS_VOICE":"语音",
				"STR_OPTIONS_SOUND":"音效",
				"STR_OPTIONS_AUTOSIT":"自动坐下",
				"STR_OPTIONS_VIBRATION":"震动",
				"STR_OPTIONS_FOLLOW":"允许好友跟踪",
				"STR_OPTIONS_INVITE":"接受邀请信息",
				"STR_OPTIONS_SEEPHOTOS":"谁能查看我的照片",
				"STR_OPTIONS_CHOSEN_YES":"是",
				"STR_OPTIONS_CHOSEN_NO":"否",
				"STR_OPTIONS_SEEPHOTOS_FRIEND":"仅仅好友可查看",
				"STR_OPTIONS_SEEPHOTOS_NOONE":"所有人都无法查看",
				"STR_OPTIONS_SEEPHOTOS_ANYONE":"任何人都可查看",
				"STR_OPTIONS_RATE":"评价游戏",
				"STR_OPTIONS_CACHE":"清除缓存",
				"STR_OPTIONS_CACHE_CONFIRM":"清除缓存将会删除您已经下载的头像，照片。您确定要清除缓存吗？",
				"STR_OPTIONS_CACHE_CLEARED":"缓存已经清理成功。",
				"STR_OPTIONS_ABOUT":"关于我们",
				"STR_OPTIONS_REPORT":"报告问题",
				"STR_OPTIONS_FOLLOWUS":"关注我们",
				"STR_OPTIONS_CONTACT":"联系我们",
				"STR_LOADING_1":"把你的朋友带到游戏中来，但也别忘了在现实中和他们一起玩。",
				"STR_LOADING_2":"与他人交流时请务必保持礼貌，在尊重别人的同时，你会得到他人的尊重。",
				"STR_LOADING_3":"永远不要尝试在牌桌上调戏荷官，不论他们有多英俊或者多性感。",
				"STR_LOADING_4":"如果在你在游戏中感受到了挫折，不要气馁，生活并没有抛弃你。",
				"STR_LOADING_5":"做任何事情都要适度，包括玩皇家德州扑克哦。",
				"STR_LOADING_6":"请记得每天打开好友信息，点击赠送筹码按键向好友赠送免费筹码。",
				"STR_LOADING_7":"轮到自己时，点击左下的筹码，可以快速选择加注金额。",
				"STR_LOADING_8":"在牌桌上查看玩家详情的时候再次点击玩家头像，就可以屏蔽烦人的玩家欧。",
				"STR_LOADING_9":"如果要和玩家私聊，请记得使用玩家详细信息界面的语音按键。",
				"STR_LOADING_10":"请不要忘记查看活动欧，说不定会有惊喜的。",
				"STR_LOADING_11":"保持连续登录，能够获得最好的奖励。",
				"STR_LOADING_END":"随时保持一颗平常心，胜利不要兴奋，失败也不要沮丧。",
				"STR_TABLEBOARD_ID":"房间ID %d 大小盲注 %s/%s",
				"STR_CARDTYPE_HIGH_CARD":"高牌",
				"STR_CARDTYPE_PAIR_CARD":"一对",
				"STR_CARDTYPE_TWO_PAIRS_CARD":"两对",
				"STR_CARDTYPE_THREE_CARD":"三条",
				"STR_CARDTYPE_STRAIGHT":"顺子",
				"STR_CARDTYPE_FLUSH":"同花",
				"STR_CARDTYPE_FULL_HOUSE":"葫芦",
				"STR_CARDTYPE_FOUR_OF_A_KIND":"四条",
				"STR_CARDTYPE_STRAIGHT_FLUSH":"同花顺",
				"STR_CARDTYPE_ROYAL_FLUSH":"皇家同花顺",
				"STR_TABLEBOARD_EXP":"经验",
				"STR_QUESTS_TITLE":"任务",
				"STR_QUESTS_RECEIVEBUTTON":"领取",
				"STR_ACHIEVEMENTS_TITLE":"成就",
				"STR_LVUP_TITLE":"恭喜",
				"STR_LVUP_TEXT":"恭喜您成功升至%d级，并且获得了%s的奖励筹码。",
				"STR_SHOP_TITLE":"商店",
				"STR_SHOP_BUTTON":"购买",
				"STR_ALMS_TITLE":"复活",
				"STR_ALMS_TEXT":"尊敬的玩家，由于您当前的钻石与筹码数过少，系统为您发放 %s 筹码。您今日还能领取 %d 次的救济金。",
				"STR_BUG_REPORT":"点击提交问题",
				"STR_BUG_INPUT":"请输入您要提交的问题",
				"STR_BUG_TIP":"您的问题已经提交服务器。我们的客服将尽快解答您的疑问",
				"STR_BUG_TIME":"提交时间",
				"STR_BUG_WAIT":"等待客服回复",
				"STR_BUG_RESPONSETIME":"回复时间",
				"STR_BUG_DELTIP":"您确定要删除这个问题吗?",
				"STR_BUG_VIEW":"查看详情",
				"STR_BUG_COMMIT":"提交",
				"STR_BUG_DELTIPDONE":"删除成功",
				"STR_BUG_DELTIPFAIL":"删除失败",
				"STR_BUG_COMMIT_TIP":"提交失败",
				"STR_POKER_ROOM_BET":"赌注 %s/%s",
				"STR_POKERTABLEBOARD_ID":"房间ID%d最小/最大 赌注%s%s",
				"STR_POKER_PRE_BET":"赌注",
				"STR_POKER_TYPE_POK9":"Pok9",
				"STR_POKER_TYPE_POK8":"Pok8",
				"STR_POKER_TYPE_TONG":"三条",
				"STR_POKER_TYPE_SAM_LUEANG":"三公",
				"STR_POKER_TYPE_STRAIGHT_FLUSH":"同花顺",
				"STR_POKER_TYPE_STRAIGHT":"顺子",
				"STR_POKER_TYPE_SCORE_0":"Score 0",
				"STR_POKER_TYPE_SCORE_1":"Score 1",
				"STR_POKER_TYPE_SCORE_2":"Score 2",
				"STR_POKER_TYPE_SCORE_3":"Score 3",
				"STR_POKER_TYPE_SCORE_4":"Score 4",
				"STR_POKER_TYPE_SCORE_5":"Score 5",
				"STR_POKER_TYPE_SCORE_6":"Score 6",
				"STR_POKER_TYPE_SCORE_7":"Score 7",
				"STR_POKER_TYPE_SCORE_8":"Score 8",
				"STR_POKER_TYPE_SCORE_0_9":"Score 0-9",
				"STR_POKER_TYPE_SCORE_9":"Score 9",
				"STR_POKER_INTRUUCE":"牌型说明",
				"STR_POKER_INTRUUCE1":"牌力大小由上至下排序",
				"STR_POKER_INTRUUCE2":"这些牌为0点",
				"STR_POKER_INTRUUCE3":"这些牌为1-9点",
				"STR_POKER_INTRUUCE4":"所有手牌点数相加，取个位数",
				"STR_POKER_INTRUUCE5":"2张初始牌为9点",
				"STR_POKER_INTRUUCE6":"2张初始牌为8点",
				"STR_POKER_INTRUUCE7":"KA2、A23不是顺子",
				"STR_POKER_INTRUUCE8":"牌型的赔率倍数",
				"STR_POKER_INTRUUCE9":"2张同花",
				"STR_POKER_INTRUUCE10":"3张同花",
				"STR_POKER_INTRUUCE11":"本局游戏结束后，将离开座位",
				"STR_POKER_INTRUUCE12":"本局游戏结束后，将离开座位并退出房间",
				"STR_WIN_STREAK":"连胜:",
				"STR_PLAYER":"玩家",
				"STR_DEAR":"庄家",
				"STR_GAME_GOTODEAR":"点击上庄",
				"STR_CHIP_NOT_ENOUGH":"筹码不足,至少%s筹码才能上庄,是否去商店？",
				"STR_POKERTABLEBOARD_ID1":"最小/最大 赌注%s/%s",
				"STR_GAME_GOTODEAR_1":"上庄成功，需要连续坐庄5场才能离座",
				"STR_GAME_GOTODEAR_2":"一位玩家上庄成功",
				"STR_STATIC_BIGWIN":"最大赢取:",
				"STR_CARDTYPE100":"3卡组 JQK",
				"STR_CARDTYPE101":"同花顺",
				"STR_CARDTYPE102":"一对",
				"STR_CARDTYPE103":"顺子",
				"STR_CARDTYPE104":"3张牌是顺序",
				"STR_ADDFRIEND_ONESELF":"您的好友数目已经达到了上限。您可以去商城购买通讯录来提升好友上限。",
				"STR_ADDFRIEND_OTHERS":"很遗憾，对方玩家的好友数目已经达到上限了。您现在无法把他加为好友。",
				"STR_MESSRECEIVE_UNDONE":"该消息中附带的所有物品已经被您领取过了。",
				"STR_LOGIN_WORNING":"您的账号已经被冻结。如果您有任何疑问，请发送邮件到我们的客服邮箱。",
				"STR_LOGIN_INFO_ERROR":"您输入的账号或密码有错误。请检查后重新输入。",
				"STR_LOGIN_INFO_NULL":"登录账号或密码不能为空，请输入。",
				"STR_LOGIN_EMALL_REGISTERED":"您输入的邮箱地址已经被注册。请重新输入可使用的邮箱地址。",
				"STR_LOGIN_EMAIL_ERROR":"您输入的邮箱格式有错误。请检查后重新输入。",
				"STR_LOGIN_PASSWORD_SHORT":"账号密码要求6-16位英文字母或数字。请重新输入您的密码。",
				"STR_LOGIN_PASSWORD_DIFFERENT":"您两次输入的密码不一致。请检查后重新输入。",
				"STR_LOGIN_PASSWORD_CHARACTER":"账号密码中不能包含除了英文字母和数字外的其他字符。请重新输入您的密码。",
				"STR_LOGIN_REGISTER_SUCCESS":"恭喜您成功注册了皇家德州扑克的账号。赶快点击OK来加入游戏吧！",
				"STR_LOGIN_RETRIEVE_SUCCESS":"密码找回邮件已经发送，请到您的邮箱中查收。如未收到，请稍等片刻再次查看。",
				"STR_LOGIN_RETRIEVE_FAIL":"您输出的账号邮箱地址没有注册。请检查并重新输入已注册的邮箱地址。",
				"STR_MAIN_LOGOFF":"您确定要登出游戏吗？",
				"STR_MAIN_QUIT":"您确定要退出游戏吗？",
				"STR_SHOP_CHIP":"您的筹码不足，想去商城买点筹码吗？",
				"STR_SHOP_DIAMOND":"您的钻石不足，想去商城买点钻石吗？",
				"STR_SHOP_BUYSUCCESSFUL":"您已经成功购买了商品 %s。",
				"STR_SHOP_REACHLIMIT":"您已经达到了该道具的购买上限。",
				"STR_SHOP_BUYFAIL":"抱歉，商品购买失败，请重试。",
				"STR_PLAYERSEARCH_SHORT":"搜索好友时请至少输入四个英文字符或数字。",
				"STR_PLAYERSEARCH_LONG":"搜索好友时至多只能输入十六个英文字符或数字。",
				"STR_FRIEND_HAVEADDED":"该玩家已经在你的好友名单里了。",
				"STR_FRIEND_LIMIT":"您的好友数量已经达到达到上限了。您可以去商城购买通讯录来提升好友上限。",
				"STR_FRIEND_FOLLOW":"您的好友 %s 正在注额 %d/%d 的房间中打牌。您确定跟踪他进入此房间吗？",
				"STR_FRIEND_DEL":"您确定要删除这名好友吗？",
				"STR_FRIEND_ADDYOURSELF":"您不能添加自身为好友。",
				"STR_PRESENT_NOTFRIEND":"只有好友之间才能赠送免费筹码。您和这位玩家还不是好友，无法赠送。",
				"STR_PRESENT_DONE":"今天您已经向这位好友赠送过免费筹码了。明天才可以再次赠送欧。",
				"STR_PERSONAL_NAME_SHORT":"您输入的昵称过短。请至少输入4个英文字母或数字。",
				"STR_PERSONAL_NAME_LONG":"您输入的昵称过长。最多能够输入16个英文字母或数字。",
				"STR_PERSONAL_NAME_REPEAK":"您输入的昵称和其他玩家的昵称重复了。请重新想个好昵称吧。",
				"STR_PERSONAL_NAME_ILLEGAL":"您输入的昵称中包含了违规字符。请只使用英文字母和数字。",
				"STR_PERSONAL_SIGNATURE_LONG":"您输入的签名过长。最多能够输入120个字符。",
				"STR_PERSONAL_RECORDING_SHORT":"您的录音时间过短。请多说点吧。",
				"STR_PERSONAL_QUICKVOICE_PLAY":"在语音播放时不能播放其他语音消息。",
				"STR_PERSONAL_QUICKVOICE_RECORD":"在语音播放时不能录入其他语音消息。",
				"STR_PERSONAL_QUICKVOICE_DEL":"您确定要删除这条快捷语音吗？",
				"STR_PERSONAL_PHOTO_DEL":"您确定要删除这张照片吗？",
				"STR_PERSONAL_PHOTO_LIMIT":"您的照片数目已经达到上限了。您可以去商城购买相册来提升照片上限。",
				"STR_PERSONAL_ACCOUNT_BINDING":"您输入的邮箱地址已经被注册。请重新输入可使用的邮箱地址。",
				"STR_PERSONAL_ITEMEXCHANGE_301002":"恭喜您，您已经成功兑换了%d个钻石，相应的碎片系统会自动扣除。",
				"STR_PERSONAL_ITEMEXCHANGE_302003":"恭喜您，您已经成功兑换了%d个放大镜，相应的碎片系统会自动扣除。",
				"STR_PERSONAL_ITEMEXCHANGE_302001":"恭喜您，您已经成功兑换了%d个麦克风到道具，相应的碎片会自动扣除。",
				"STR_PERSONAL_ITEMEXCHANGE_302002":"恭喜您，您已经成功兑换了%d个互动表情道具，相应的碎片会自动扣除。",
				"STR_PERSONAL_BINDIN":"请使用您的常用邮箱进行账号绑定。绑定后的账号能够在其他设备上游戏使用账号登录。",
				"STR_ITEM_TUREEYE_NULL":"您的放大镜数量不足，想要去商城购买一些吗？",
				"STR_REPORT_PHOTO_CONFRIM":"您确定要举报这张照片吗？有多名玩家举报此照片后，该照片将被屏蔽。我们将尽快进行审核。",
				"STR_REPORT_PHOTO_REPEAK":"您已经举报过这张照片。请不要重复举报。",
				"STR_SITDOWN_LIMIT":"此房间人数已满，无法进入。请选择其他有空位的房间。",
				"STR_SITDOWN_FULL":"这个房间没有空位。点击“YES”，系统将为您自动匹配到另一个新房间。点击“NO”，您将留在目前房间观战。",
				"STR_SITDOWN_REPEAK":"你已经在座位上了。",
				"STR_SITDOWN_NOTEMPTY":"您选择的座位已经被其他玩家占据了，请选择其他的空座位。",
				"STR_TABLE_RECORDIND_SHORT":"您录音的时间过短，请重新录音。",
				"STR_ITEM_VOICE_NULL":"您的麦克风不够了，想要去商城购买一些麦克风吗？",
				"STR_ITEM_VOICE_STAND":"您目前还未坐下，还不能够使用语音功能。",
				"STR_ITEM_CHAT_STAND":"您目前还未坐下，还不能发送文字和表情。",
				"STR_ITEM_EXPRESSION_NULL":"您的互动表情不够了，想要去商城购买一些互动表情吗？",
				"STR_TABLE_LEAVE_SEAT":"离开座位会让您失去已下注的筹码。您确定要现在离开座位吗？",
				"STR_TABLE_LEAVE_ROOM":"离开房间会让您失去已下注的筹码。您确定要现在离开房间吗？",
				"STR_INVITE_RECEIVE":"玩家 %s 邀请您参加牌局，点击确认。",
				"STR_INVITE_CONFRIM":"玩家 %s 邀请您参加他的牌局。房间ID %d，大小盲注 %s / %s。你确定要加入牌局吗？",
				"STR_INVITE_CONFRIM1":"玩家 %s 邀请您参加他的牌局。房间ID %d，赌注 %s / %s。你确定要加入牌局吗？",
				"STR_INVITE_SAMEROOM":"您和该玩家已经在同一房间中了。",
				"STR_MISSION_COMPLETE":"您完成了一个任务，快去领取奖励吧。",
				"STR_MUTE_ON":"您已成功开启静音功能。",
				"STR_MUTE_OFF":"您已成功关闭静音功能。",
				"STR_EQUIPMENT_MICROPHONE":"启动麦克风功能失败，请允许本游戏使用手机麦克风功能。请检查手机设置。",
				"STR_ACHIEVEMENT_SUCCESS":"恭喜！您成功领取了成就奖励 %d %s.",
				"STR_LOGIN_OTHERDEVICES":"您的账号已经在其他地方登录了。请检查您的账号密码安全，以避免损失。如果您有任何疑问，请发送邮件到我们的客服邮箱。",
				"STR_NETWORK_REQUEST":"发生错误%d, 网络请求失败。请检查您的网络环境，并稍后尝试。",
				"STR_NETWORK_ERROR_CHECK":"网络发生错误,连接断开。请检查您的设备或网络设置.",
				"STR_UNKNOWN_ERROR":"发生未知错误，游戏无法正常进行。您可以通过我们的客服邮箱告知我们错误情况。",
				"STR_ERROR_DATA":"出现数据错误，请退回至登陆界面重新登录游戏。",
				"STR_EVALUATION_TEXT":"尊敬的玩家，您现在可以对我们的游戏进行评价了，进行评价后您将会获得奖励。请问是否跳转至相关页面？",
				"STR_GOOGLEPLAY_ERROR_1":"进行购买操作时所需的一项或多项 Google Play 服务目前无法使用。",
				"STR_GOOGLEPLAY_ERROR_2":"更新Google Play服务后才能进行购买。",
				"STR_GOOGLEPLAY_ERROR_3":"您的手机中没有Google Play服务，您必须先安装该服务才能进行购买。",
				"STR_GOOGLEPLAY_ERROR_4":"您必须先启用Google Play服务才能进行购买。",
				"STR_ITEM_NAME_301001":"筹码",
				"STR_ITEM_NAME_301002":"钻石",
				"STR_ITEM_NAME_302001":"麦克风",
				"STR_ITEM_NAME_302002":"互动表情",
				"STR_ITEM_NAME_302003":"放大镜",
				"STR_ITEM_NAME_303001":"金筹码",
				"STR_ITEM_NAME_304001":"通讯录",
				"STR_ITEM_NAME_304002":"相册",
				"STR_ITEM_DESC_301001":"表示玩家的筹码个数，财富衡量单位",
				"STR_ITEM_DESC_301002":"表示玩家的钻石个数，财富衡量单位",
				"STR_ITEM_DESC_302001":"使用语音功能需要消耗的道具，每使用1次语音消耗1个。",
				"STR_ITEM_DESC_302002":"使用互动表情需要消耗的道具，每使用1次互动表情消耗1个。",
				"STR_ITEM_DESC_302003":"使用后可以查看玩家的游戏数据，每查看1名玩家消耗1个，效果持续 %d 分钟。",
				"STR_ITEM_DESC_303001":"增加任务筹码奖励的道具，所有任务的筹码奖励变为 %s 倍，持续 %d 天。",
				"STR_ITEM_DESC_304001":"提升好友数量上限的道具。初始上限为 %d 个好友。每拥有1个通讯录，上限提升 %d 个。",
				"STR_ITEM_DESC_304002":"提升照片数量上限的道具。初始上限为 %d 张照片。每拥有1个相册，上限提升 %d 个。",
				"STR_GOODS_NAME_401001":"%d 钻石包",
				"STR_GOODS_NAME_401002":"%d 钻石包",
				"STR_GOODS_NAME_401003":"%d 钻石包",
				"STR_GOODS_NAME_401004":"%d 钻石包",
				"STR_GOODS_NAME_402001":"%d 筹码包",
				"STR_GOODS_NAME_402002":"%d 筹码包",
				"STR_GOODS_NAME_402003":"%d 筹码包",
				"STR_GOODS_NAME_402004":"%d 筹码包",
				"STR_GOODS_NAME_403001":"%d 麦克风包",
				"STR_GOODS_NAME_403002":"%d 麦克风包",
				"STR_GOODS_NAME_404001":"%d 表情包",
				"STR_GOODS_NAME_404002":"%d 表情包",
				"STR_GOODS_NAME_405001":"%d 放大镜包",
				"STR_GOODS_NAME_406001":"金筹码",
				"STR_GOODS_NAME_407001":"通讯录",
				"STR_GOODS_NAME_408001":"相册",
				"STR_GOODS_DESC_401001":"%d 个钻石",
				"STR_GOODS_DESC_401002":"%d 个钻石",
				"STR_GOODS_DESC_401003":"%d 个钻石",
				"STR_GOODS_DESC_401004":"%d 个钻石",
				"STR_GOODS_DESC_402001":"%d 个筹码",
				"STR_GOODS_DESC_402002":"%d 个筹码",
				"STR_GOODS_DESC_402003":"%d 个筹码",
				"STR_GOODS_DESC_402004":"%d 个筹码",
				"STR_GOODS_DESC_403001":"%d 个麦克风。使用语音功能需要消耗的道具，每使用1次语音消耗1个。",
				"STR_GOODS_DESC_403002":"%d 个麦克风。使用语音功能需要消耗的道具，每使用1次语音消耗1个。",
				"STR_GOODS_DESC_404001":"%d 个互动表情。使用互动表情需要消耗的道具，每使用1次互动表情消耗1个。",
				"STR_GOODS_DESC_404002":"%d 个互动表情。使用互动表情需要消耗的道具，每使用1次互动表情消耗1个。",
				"STR_GOODS_DESC_405001":"%d 个放大镜。使用后可以查看玩家的游戏数据，每查看1名玩家消耗1个，效果持续 %d 分钟。",
				"STR_GOODS_DESC_406001":"增加任务筹码奖励的道具，所有任务的筹码奖励变为 %d 倍，持续 %d 天。多次购买，持续时间加长。",
				"STR_GOODS_DESC_407001":"提升好友数量上限的道具。初始上限为 %d 个好友。每拥有1个通讯录，上限提升 %d 个。最多购买 %d个，价格根据购买数变化。",
				"STR_GOODS_DESC_408001":"提升照片数量上限的道具。初始上限为 %d 张照片。每拥有1个相册，上限提升 %d 个。最多购买 %d个，价格根据购买数变化",
				"STR_QUEST_DESC_101101":"完成3盘牌局",
				"STR_QUEST_DESC_101201":"游戏时间经过5分钟",
				"STR_QUEST_DESC_102101":"赢得2盘牌局",
				"STR_QUEST_DESC_102201":"在Preflop圈就赢得牌局3次",
				"STR_QUEST_DESC_102301":"亮牌赢得牌局2次",
				"STR_QUEST_DESC_103101":"赢取的筹码（未抽成前）是本局投入筹码的5倍以上,1次",
				"STR_QUEST_DESC_104101":"在4个奖池以上的牌局中赢的全部奖池，1次",
				"STR_QUEST_DESC_105101":"ALL IN后赢得牌局3次",
				"STR_QUEST_DESC_106101":"5人及其以上ALL IN，并最终赢得牌局,1次",
				"STR_QUEST_DESC_107101":"亮牌时，以同样的牌型击败其他玩家，1次",
				"STR_QUEST_DESC_108101":"亮牌时，以高牌牌型赢得1次牌局",
				"STR_QUEST_DESC_108201":"亮牌时，以一对牌型赢得1次牌局",
				"STR_QUEST_DESC_108301":"亮牌时，以两对牌型赢得1次牌局",
				"STR_QUEST_DESC_108401":"亮牌时，以三条牌型赢得1次牌局",
				"STR_QUEST_DESC_108501":"亮牌时，以顺子牌型赢得1次牌局",
				"STR_QUEST_DESC_108601":"亮牌时，以同花牌型赢得1次牌局",
				"STR_QUEST_DESC_108701":"亮牌时，以葫芦牌型赢得1次牌局",
				"STR_QUEST_DESC_109101":"聊天（包括表情，文字，互动表情，语音）20次",
				"STR_QUEST_DESC_110101":"评论玩家的照片5次",
				"STR_QUEST_DESC_101102":"完成10盘牌局",
				"STR_QUEST_DESC_101202":"游戏时间经过15分钟",
				"STR_QUEST_DESC_102102":"赢得5盘牌局",
				"STR_QUEST_DESC_102202":"在Preflop圈就赢得牌局9次",
				"STR_QUEST_DESC_102302":"亮牌赢得牌局5次",
				"STR_QUEST_DESC_103102":"赢取的筹码（未抽成前）是本局投入筹码的5倍以上,3次",
				"STR_QUEST_DESC_104102":"在4个奖池以上的牌局中赢的全部奖池，2次",
				"STR_QUEST_DESC_105102":"ALL IN后赢得牌局9次",
				"STR_QUEST_DESC_106102":"5人及其以上ALL IN，并最终赢得牌局,2次",
				"STR_QUEST_DESC_107102":"亮牌时，以同样的牌型击败其他玩家，2次",
				"STR_QUEST_DESC_108102":"亮牌时，以高牌牌型赢得2次牌局",
				"STR_QUEST_DESC_108202":"亮牌时，以一对牌型赢得2次牌局",
				"STR_QUEST_DESC_108302":"亮牌时，以两对牌型赢得2次牌局",
				"STR_QUEST_DESC_108402":"亮牌时，以三条牌型赢得2次牌局",
				"STR_QUEST_DESC_108502":"亮牌时，以顺子牌型赢得2次牌局",
				"STR_QUEST_DESC_108602":"亮牌时，以同花牌型赢得2次牌局",
				"STR_QUEST_DESC_108702":"亮牌时，以葫芦牌型赢得2次牌局",
				"STR_QUEST_DESC_109102":"聊天（包括表情，文字，互动表情，语音）50次",
				"STR_QUEST_DESC_110102":"评论玩家的照片25次",
				"STR_QUEST_DESC_101103":"完成30盘牌局",
				"STR_QUEST_DESC_101203":"游戏时间经过30分钟",
				"STR_QUEST_DESC_102103":"赢得10盘牌局",
				"STR_QUEST_DESC_102203":"在Preflop圈就赢得牌局15次",
				"STR_QUEST_DESC_102303":"亮牌赢得牌局10次",
				"STR_QUEST_DESC_103103":"赢取的筹码（未抽成前）是本局投入筹码的5倍以上,5次",
				"STR_QUEST_DESC_104103":"在4个奖池以上的牌局中赢的全部奖池，3次",
				"STR_QUEST_DESC_105103":"ALL IN后赢得牌局15次",
				"STR_QUEST_DESC_106103":"5人及其以上ALL IN，并最终赢得牌局,3次",
				"STR_QUEST_DESC_107103":"亮牌时，以同样的牌型击败其他玩家，3次",
				"STR_QUEST_DESC_108103":"亮牌时，以高牌牌型赢得3次牌局",
				"STR_QUEST_DESC_108203":"亮牌时，以一对牌型赢得3次牌局",
				"STR_QUEST_DESC_108303":"亮牌时，以两对牌型赢得3次牌局",
				"STR_QUEST_DESC_108403":"亮牌时，以三条牌型赢得3次牌局",
				"STR_QUEST_DESC_108503":"亮牌时，以顺子牌型赢得3次牌局",
				"STR_QUEST_DESC_108603":"亮牌时，以同花牌型赢得3次牌局",
				"STR_QUEST_DESC_108703":"亮牌时，以葫芦牌型赢得3次牌局",
				"STR_QUEST_DESC_109103":"聊天（包括表情，文字，互动表情，语音）100次",
				"STR_QUEST_DESC_110103":"评论玩家的照片50次",
				"STR_ACHIVEVMENT_DESC_201001":"等级达到5级",
				"STR_ACHIVEVMENT_DESC_201002":"等级达到10级",
				"STR_ACHIVEVMENT_DESC_201003":"等级达到20级",
				"STR_ACHIVEVMENT_DESC_201004":"等级达到35级",
				"STR_ACHIVEVMENT_DESC_201005":"等级达到50级",
				"STR_ACHIVEVMENT_DESC_202001":"资产总量达到100万",
				"STR_ACHIVEVMENT_DESC_202002":"资产总量达到1000万",
				"STR_ACHIVEVMENT_DESC_202003":"资产总量达到1亿",
				"STR_ACHIVEVMENT_DESC_202004":"资产总量达到10亿",
				"STR_ACHIVEVMENT_DESC_202005":"资产总量达到100亿",
				"STR_ACHIVEVMENT_DESC_203001":"完成50场牌局",
				"STR_ACHIVEVMENT_DESC_203002":"完成500场牌局",
				"STR_ACHIVEVMENT_DESC_203003":"完成2500场牌局",
				"STR_ACHIVEVMENT_DESC_203004":"完成10000场牌局",
				"STR_ACHIVEVMENT_DESC_203005":"完成25000场牌局",
				"STR_ACHIVEVMENT_DESC_203006":"完成50000场牌局",
				"STR_ACHIVEVMENT_DESC_203007":"完成100000场牌局",
				"STR_ACHIVEVMENT_DESC_204001":"赢得10次牌局",
				"STR_ACHIVEVMENT_DESC_204002":"赢得100次牌局",
				"STR_ACHIVEVMENT_DESC_204003":"赢得500次牌局",
				"STR_ACHIVEVMENT_DESC_204004":"赢得2000次牌局",
				"STR_ACHIVEVMENT_DESC_204005":"赢得5000次牌局",
				"STR_ACHIVEVMENT_DESC_204006":"赢得10000次牌局",
				"STR_ACHIVEVMENT_DESC_204007":"赢得20000次牌局",
				"STR_ACHIVEVMENT_DESC_205001":"在Preflop圈就赢的牌局达到5场",
				"STR_ACHIVEVMENT_DESC_205002":"在Preflop圈就赢的牌局达到50场",
				"STR_ACHIVEVMENT_DESC_205003":"在Preflop圈就赢的牌局达到500场",
				"STR_ACHIVEVMENT_DESC_205004":"在Preflop圈就赢的牌局达到2500场",
				"STR_ACHIVEVMENT_DESC_205005":"在Preflop圈就赢的牌局达到10000场",
				"STR_ACHIVEVMENT_DESC_206001":"ALL IN后并最终赢牌的牌局达到5场",
				"STR_ACHIVEVMENT_DESC_206002":"ALL IN后并最终赢牌的牌局达到50场",
				"STR_ACHIVEVMENT_DESC_206003":"ALL IN后并最终赢牌的牌局达到500场",
				"STR_ACHIVEVMENT_DESC_206004":"ALL IN后并最终赢牌的牌局达到2500场",
				"STR_ACHIVEVMENT_DESC_206005":"ALL IN后并最终赢牌的牌局达到10000场",
				"STR_ACHIVEVMENT_DESC_207001":"亮牌时，以高牌牌型赢得牌局达到5场",
				"STR_ACHIVEVMENT_DESC_207002":"亮牌时，以高牌牌型赢得牌局达到50场",
				"STR_ACHIVEVMENT_DESC_207003":"亮牌时，以高牌牌型赢得牌局达到250场",
				"STR_ACHIVEVMENT_DESC_207004":"亮牌时，以高牌牌型赢得牌局达到1000场",
				"STR_ACHIVEVMENT_DESC_207005":"亮牌时，以高牌牌型赢得牌局达到3000场",
				"STR_ACHIVEVMENT_DESC_208001":"亮牌时，以一对牌型赢得牌局达到5场",
				"STR_ACHIVEVMENT_DESC_208002":"亮牌时，以一对牌型赢得牌局达到50场",
				"STR_ACHIVEVMENT_DESC_208003":"亮牌时，以一对牌型赢得牌局达到500场",
				"STR_ACHIVEVMENT_DESC_208004":"亮牌时，以一对牌型赢得牌局达到2000场",
				"STR_ACHIVEVMENT_DESC_208005":"亮牌时，以一对牌型赢得牌局达到5000场",
				"STR_ACHIVEVMENT_DESC_209001":"亮牌时，以两对牌型赢得牌局达到5场",
				"STR_ACHIVEVMENT_DESC_209002":"亮牌时，以两对牌型赢得牌局达到50场",
				"STR_ACHIVEVMENT_DESC_209003":"亮牌时，以两对牌型赢得牌局达到500场",
				"STR_ACHIVEVMENT_DESC_209004":"亮牌时，以两对牌型赢得牌局达到2000场",
				"STR_ACHIVEVMENT_DESC_209005":"亮牌时，以两对牌型赢得牌局达到5000场",
				"STR_ACHIVEVMENT_DESC_210001":"亮牌时，以三条牌型赢得牌局达到5场",
				"STR_ACHIVEVMENT_DESC_210002":"亮牌时，以三条牌型赢得牌局达到50场",
				"STR_ACHIVEVMENT_DESC_210003":"亮牌时，以三条牌型赢得牌局达到500场",
				"STR_ACHIVEVMENT_DESC_210004":"亮牌时，以三条牌型赢得牌局达到2000场",
				"STR_ACHIVEVMENT_DESC_210005":"亮牌时，以三条牌型赢得牌局达到5000场",
				"STR_ACHIVEVMENT_DESC_211001":"亮牌时，以顺子牌型赢得牌局达到5场",
				"STR_ACHIVEVMENT_DESC_211002":"亮牌时，以顺子牌型赢得牌局达到50场",
				"STR_ACHIVEVMENT_DESC_211003":"亮牌时，以顺子牌型赢得牌局达到500场",
				"STR_ACHIVEVMENT_DESC_211004":"亮牌时，以顺子牌型赢得牌局达到2000场",
				"STR_ACHIVEVMENT_DESC_211005":"亮牌时，以顺子牌型赢得牌局达到5000场",
				"STR_ACHIVEVMENT_DESC_212001":"亮牌时，以同花牌型赢得牌局达到5场",
				"STR_ACHIVEVMENT_DESC_212002":"亮牌时，以同花牌型赢得牌局达到50场",
				"STR_ACHIVEVMENT_DESC_212003":"亮牌时，以同花牌型赢得牌局达到250场",
				"STR_ACHIVEVMENT_DESC_212004":"亮牌时，以同花牌型赢得牌局达到1000场",
				"STR_ACHIVEVMENT_DESC_212005":"亮牌时，以同花牌型赢得牌局达到3000场",
				"STR_ACHIVEVMENT_DESC_213001":"亮牌时，以葫芦牌型赢得牌局达到3场",
				"STR_ACHIVEVMENT_DESC_213002":"亮牌时，以葫芦牌型赢得牌局达到30场",
				"STR_ACHIVEVMENT_DESC_213003":"亮牌时，以葫芦牌型赢得牌局达到200场",
				"STR_ACHIVEVMENT_DESC_213004":"亮牌时，以葫芦牌型赢得牌局达到500场",
				"STR_ACHIVEVMENT_DESC_213005":"亮牌时，以葫芦牌型赢得牌局达到1000场",
				"STR_ACHIVEVMENT_DESC_214001":"亮牌时，以四条牌型赢得牌局达到2场",
				"STR_ACHIVEVMENT_DESC_214002":"亮牌时，以四条牌型赢得牌局达到10场",
				"STR_ACHIVEVMENT_DESC_214003":"亮牌时，以四条牌型赢得牌局达到50场",
				"STR_ACHIVEVMENT_DESC_214004":"亮牌时，以四条牌型赢得牌局达到200场",
				"STR_ACHIVEVMENT_DESC_214005":"亮牌时，以四条牌型赢得牌局达到500场",
				"STR_ACHIVEVMENT_DESC_215001":"亮牌时，获得过所有数字的四条，从A到K",
				"STR_ACHIVEVMENT_DESC_216001":"亮牌时，以同花顺牌型赢得牌局达到1场",
				"STR_ACHIVEVMENT_DESC_216002":"亮牌时，以同花顺牌型赢得牌局达到5场",
				"STR_ACHIVEVMENT_DESC_216003":"亮牌时，以同花顺牌型赢得牌局达到20场",
				"STR_ACHIVEVMENT_DESC_216004":"亮牌时，以同花顺牌型赢得牌局达到50场",
				"STR_ACHIVEVMENT_DESC_216005":"亮牌时，以同花顺牌型赢得牌局达到100场",
				"STR_ACHIVEVMENT_DESC_217001":"亮牌时，以皇家同花顺牌型赢得牌局达到1场",
				"STR_ACHIVEVMENT_DESC_217002":"亮牌时，以皇家同花顺牌型赢得牌局达到2场",
				"STR_ACHIVEVMENT_DESC_217003":"亮牌时，以皇家同花顺牌型赢得牌局达到5场",
				"STR_ACHIVEVMENT_DESC_217004":"亮牌时，以皇家同花顺牌型赢得牌局达到10场",
				"STR_ACHIVEVMENT_DESC_217005":"亮牌时，以皇家同花顺牌型赢得牌局达到20场",
				"STR_ACHIVEVMENT_DESC_218001":"获得所有花色的皇家同花顺",
				"STR_ACHIVEVMENT_DESC_219001":"使用20次语音",
				"STR_ACHIVEVMENT_DESC_219002":"使用100次语音",
				"STR_ACHIVEVMENT_DESC_219003":"使用500次语音",
				"STR_ACHIVEVMENT_DESC_219004":"使用2500次语音",
				"STR_ACHIVEVMENT_DESC_219005":"使用10000次语音",
				"STR_ACHIVEVMENT_DESC_220001":"使用50次互动表情",
				"STR_ACHIVEVMENT_DESC_220002":"使用250次互动表情",
				"STR_ACHIVEVMENT_DESC_220003":"使用1000次互动表情",
				"STR_ACHIVEVMENT_DESC_220004":"使用5000次互动表情",
				"STR_ACHIVEVMENT_DESC_220005":"使用20000次互动表情",
				"STR_ACHIVEVMENT_DESC_221001":"好友数量达到5人",
				"STR_ACHIVEVMENT_DESC_221002":"好友数量达到20人",
				"STR_ACHIVEVMENT_DESC_221003":"好友数量达到50人",
				"STR_ACHIVEVMENT_DESC_222001":"上传过1张照片",
				"STR_ACHIVEVMENT_DESC_222002":"上传过10张照片",
				"STR_ACHIVEVMENT_DESC_222003":"上传过100张照片",
				"STR_ACHIVEVMENT_DESC_223001":"得到5个赞",
				"STR_ACHIVEVMENT_DESC_223002":"得到50个赞",
				"STR_ACHIVEVMENT_DESC_223003":"得到500个赞",
				"STR_ACHIVEVMENT_DESC_224001":"送出5个赞",
				"STR_ACHIVEVMENT_DESC_224002":"送出50个赞",
				"STR_ACHIVEVMENT_DESC_224003":"送出500个赞",
				"STR_ACHIVEVMENT_DESC_225001":"自己的照片获得评论10次",
				"STR_ACHIVEVMENT_DESC_225002":"自己的照片获得评论100次",
				"STR_ACHIVEVMENT_DESC_225003":"自己的照片获得评论1000次",
				"STR_ACHIVEVMENT_DESC_226001":"评论其他人照片10次",
				"STR_ACHIVEVMENT_DESC_226002":"评论其他人照片100次",
				"STR_ACHIVEVMENT_DESC_226003":"评论其他人照片1000次",
				"STR_ACHIVEVMENT_DESC_227001":"完成5个任务",
				"STR_ACHIVEVMENT_DESC_227002":"完成50个任务",
				"STR_ACHIVEVMENT_DESC_227003":"完成500个任务",
				"STR_ACHIVEVMENT_DESC_227004":"完成2500个任务",
				"STR_ACHIVEVMENT_DESC_227005":"完成10000个任务",
				"STR_ACHIVEVMENT_DESC_228001":"兑换5次道具",
				"STR_ACHIVEVMENT_DESC_228002":"兑换50次道具",
				"STR_ACHIVEVMENT_DESC_228003":"兑换500次道具",
				"STR_ACHIVEVMENT_DESC_229001":"牌桌上赠送其他玩家筹码10次",
				"STR_ACHIVEVMENT_DESC_229002":"牌桌上赠送其他玩家筹码100次",
				"STR_ACHIVEVMENT_DESC_229003":"牌桌上赠送其他玩家筹码1000次",
				"STR_ACHIVEVMENT_DESC_230001":"赠送好友免费筹码10次",
				"STR_ACHIVEVMENT_DESC_230002":"赠送好友免费筹码100次",
				"STR_ACHIVEVMENT_DESC_230003":"赠送好友免费筹码1000次",
				"STR_ACHIVEVMENT_DESC_231001":"获得免费筹码总量达到10万",
				"STR_ACHIVEVMENT_DESC_231002":"获得免费筹码总量达到25万",
				"STR_ACHIVEVMENT_DESC_231003":"获得免费筹码总量达到100万",
				"STR_ACHIVEVMENT_DESC_232001":"累计登陆天数达到5天",
				"STR_ACHIVEVMENT_DESC_232002":"累计登陆天数达到25天",
				"STR_ACHIVEVMENT_DESC_232003":"累计登陆天数达到100天",
				"STR_ACHIVEVMENT_DESC_232004":"累计登陆天数达到250天",
				"STR_ACHIVEVMENT_DESC_232005":"累计登陆天数达到500天",
				"STR_LOGIN_VERSION":"版本号：",
				"STR_INFORMATION_PERSONAL_SIGNATURE_DEFAULT":"这位玩家还没有留下任何笔迹。想更引人关注吗？留下一段个性签名吧。",
				"STR_MESS_EVALUATION_TITLE":"感谢您的评价",
				"STR_MESS_EVALUATION_CONTENT":"因为您对于我们游戏的支持与评价，系统为您发放%d筹码的奖励，请及时领取。",
    
};
